### ISSUE TITLE
Date FACTURATION = Date DEPART

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#10]
Par défaut, DATE FACTURATION = DATE DEPART
Et laisser champ DATE FACTURATION ouvert.
Quand DATE DEPART rentré, générer automatiquement DATE FACTURATION

**Comment by MamboJoel** [comment]
> Par défaut, DATE FACTURATION = DATE DEPART

Cette réglé était déjà implémentée. Je m'étonne donc que tu la demandes. Est-ce que tu peux m'écrire une scénario pour que je constate l'anomalie ? 

> Et laisser champ DATE FACTURATION ouvert.

Ok.

> Quand DATE DEPART rentré, générer automatiquement DATE FACTURATION

Ok. Quand Départ est entrée, on l'assigne aussi à Facturation.

**Comment by josneaulgi** [comment]
Est-ce possible que quand on rentre la DATE DEPART que la DATE FACTURATION sorte simultanément ? Car on ne la voit pas ressortir de suite et du coup on retape la même date dans DATE FACTURATION.

**Comment by josneaulgi** [comment]
Bonjour,
ça ne marche pas. Quand on passe en statut facturé, les DATE DEPART et DATE FACTURATION n'apparaissent pas. Peux-tu vérifier stp?

**Comment by MamboJoel** [comment]
On a changé deux choses :

- Si vous n'entrez pas de date de facturation mais que vous passez en "Facturé", automatiquement on assigne la date du jour aux dates de facturation et de départ.

- Lorsque vous tapez une valeur dans le champ date de facturation, aussitôt cette valeur est assignée à la date de départ.

Est-ce que ça te convient ? Si oui tu peux clore cette issue.

**Comment by josneaulgi** [comment]
ça ne marche pas, quand on passe en statut "Facturé", les dates de facturation et de départ ne s'affichent pas.
merci de vérifier.
