### ISSUE TITLE
Logique métier de la prestation de service

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#101]
Quand dans le formulaire du produit le champ prestation de service est tagué, il faut que désormais tous les kart soient achat LGI et non pas achat embouteilleur.

**Comment by josneaulgi** [comment]
Ca ne marche toujours pas.

**Comment by MamboJoel** [comment]
Est-ce que tu peux effectuer un test ?

**Comment by josneaulgi** [comment]
OK
