### ISSUE TITLE
Impossible automatisation onglet "Formulaire"

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#103]
Message d'erreur lors de l'automatisation dans l'onglet "Formulaire" de la Fiche n°28659

Merci

**Comment by Portekoi** [comment]
Je n'ai pas compris le problème. Il me faudrait le déroulement pour reproduire l'erreur. Merci

**Comment by lgiRomain** [comment]
Sur la ficher produit n°28659, aller sur le deuxième onglet nommé "Formulaire", puis cliquer sur le bouto, "Automatiser". Un message d'erreur s'affiche.

Merci

**Comment by Portekoi** [comment]
Ok je pense que c'est lié à cette correction : 
https://github.com/ntlm-technologies/lgi-pinard/commit/3eb1974e83f10d38a51218e2b1d4d0e03117ecb7

Je corrige.

**Comment by MamboJoel** [comment]
En effet, il y a une erreur de cast ligne 188 de `Waybis.Pinard.BaseProduct`. Merci Damien.

**Comment by Portekoi** [comment]
Ok c'est publié
