### ISSUE TITLE
BUG NOMBRE DE PALETTES SUR PACKING LIST

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#105]
Quand on force le nombre de palettes sur le formulaire de la commande, cela ne s'automatise pas sur la packing list VGM !!
http://lgivm.waybis.com/Kart/Form.aspx?KartID=33657
http://lgivm.waybis.com/Kart/PackingList.aspx?KartID=33657

**Comment by Portekoi** [comment]
Je regarde. C'est lié à cette demande :
https://github.com/lgi-wines/Extranet-LGI/issues/99

**Comment by Portekoi** [comment]
@josneaulgi J'aurais besoin de plus d'infos dans le cas où la commande contient 2 types de palette et que vous en forcer le nombre. Comment répartir entre les deux modèles?

**Comment by josneaulgi** [comment]
ça n'arrive pas quand il y a plusieurs types de palettes

**Comment by Portekoi** [comment]
Ok merci. Je corrige.

**Comment by Portekoi** [comment]
C'est corrigé
