### ISSUE TITLE
BUG : degré d'alcool n'apparaît plus dans la delivery note

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#107]
je viens de saisir une nouvelle commande et je vois que le degré d'alcool n'apparaît plus dans la delivery note.
http://lgivm.waybis.com/Kart/DeliveryNote.aspx?KartID=34058

**Comment by Portekoi** [comment]
Je regarde

**Comment by Portekoi** [comment]
J'ai corrigé mais je ne peux pas publier. J'ai des problèmes de connexion. Je vous dis dès que c'est bon.

**Comment by Portekoi** [comment]
C'est livré
