### ISSUE TITLE
CHANGEMENT N° FAX

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#11]
04 68 11 93 14 => 04 68 77 83 77
00 33 4 68 11 93 14 => 00 33 4 68 77 83 77

Modifs de 6 supports 
1- Bon de Livraison
2- Facture
3- Conf. Transporteur (client) = > Etat à supprimer définitivement
4- Conf. Transport (trans)
5- Packing List
6- Bon de retiraison

**Comment by MamboJoel** [comment]
C'est bon Stéphanie.
