### ISSUE TITLE
OPIMIAN 2017 / Archivage et duplication des fiches produits

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#113]
Comme chaque année.

Client souche dans lequel se trouvent les 7 "Produits ACTIFS" **Opimian 2017** à dupliquer est 👍 THE OPIMIAN SOCIETE ClientID=88.
Sur ce client, 7 PRODUITS sont activés avec **PV** et **Commissions AGENTS**.

**Etape 1 :** Archivage de toutes les fiches actives des 9 clients suivants :
•        ClientID : 68
•        ClientID : 148
•        ClientID : 206
•        ClientID : 208
•        ClientID : 209
•        ClientID : 211
•        ClientID : 212
•        ClientID : 213 
•        ClientID : 214

**Etape 2** : Copies intégrales (avec PV et Commissions AGENTS) des 7 Produits "Actifs" du ClientID=88 dans les 9 autres clients

Sont à copier intégralement les 7 ProductID suivants :
·        ProductID : 28542
·        ProductID : 28544
·        ProductID : 28545
·        ProductID : 28587
·        ProductID : 28588
·        ProductID : 28589
·        ProductID : 28590

Dans les 9 ClientsID suivants :
•        ClientID : 68
•        ClientID : 148
•        ClientID : 206
•        ClientID : 208
•        ClientID : 209
•        ClientID : 211
•        ClientID : 212
•        ClientID : 213
•        ClientID : 214

**Etape 3** : Enlever « Copie de » dans la désignation des produits

**Comment by MamboJoel** [comment]
C'est ok.
