### ISSUE TITLE
URGENT Problème édition facture

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#116]
sur la kartID 34449, je ne peux pas éditer de facture négoce, ça me met facture proforma.
http://lgivm.waybis.com/Kart/Form.aspx?KartID=34449

**Comment by Portekoi** [comment]
A priori, cela vient d'un produit qui est en attente de validation.

**Comment by josneaulgi** [comment]
Pas possible car on ne saisit que des produits actifs

**Comment by josneaulgi** [comment]
Ca vient de me le refaire avec la 34369
http://lgivm.waybis.com/Kart/Form.aspx?KartID=34369

**Comment by Portekoi** [comment]
Le `Kart` est bien tagué comme `HasToValidate` du fait de produit(s) qui semblent à l'état `ToValidate`

Et si je regarde le produit concerné pour le `Kart` `34369  `: 
http://lgivm.waybis.com/Product/ComponentList.aspx?ProductID=25552

Il est bien en `Ce produit a été modifié depuis la dernière validation par l'ADV.`

Pour le premier `Kart` `34449`, ce même produit est aussi présent.

**Comment by josneaulgi** [comment]
OK C'est bon
