### ISSUE TITLE
Système d'appro LGI2 - Problème de confidentialité

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#117]
### Description
Céline a créé 2 nouveaux comptes sur le système d'appro pour un nouvel imprimeur (imprimerie Etienne). Céline leur a logiquement donnée accès uniquement aux commandes pour Etienne.

### Scénario pour reproduire l'anomalie
Se connecter au système d'appro avec leur compte: ID=vlung ; PW=232approLGI29. 

### Résultat attendu
L'utilisateur ne doit pas avoir accès aux autres commandes (uniquement Etienne) et ne doivent pas voir les statuts "Projet", "Commande reçue", "Commande facturée" et "Commande annulée".
![capture d ecran 1](https://user-images.githubusercontent.com/28759009/30376309-0a64ce28-988c-11e7-905b-f54da598af4c.png)

### Anomalie constatée
L'utilisateur à accès à tous de chez lui, mais chez LGI (postes de Céline et de Romain), quand on se connecte sur le compte vlung, les restrictions sont bien place

**Comment by Portekoi** [comment]
Je regarde. A priori, cela ne se produit qu'à la première connexion.

Pour reproduire à chaque fois, il suffit de se connecter en navigation privée.

**Comment by Portekoi** [comment]
J'ai trouvé. Je vois avec Nico pour livrer dès que possible.

**Comment by Portekoi** [comment]
J'ai trouvé. Je vois avec Nico pour livrer dès que possible.

**Comment by lgiRomain** [comment]
Ok merci de me prévenir lorsque ce sera réglé

**Comment by Portekoi** [comment]
@lgiRomain : C'est livré. Un CTRL + F5 sera peut être nécessaire.

**Comment by lgiRomain** [comment]
@Portekoi c'est réglé pour les 2 utilisateurs en question. Merci.
ATTENTION: j'ai l'impression que ton intervention à modifier quelques paramètres sur nos comptes en interne (au moins). Ex: quand on filtre sur un statut particulier, on clique sur "Chercher", les statuts reviennent tous sur le statut cochés. A suivre (je laisse l'issue ouvert le temps d'avoir d'autres défauts éventuels)

**Comment by Portekoi** [comment]
OK je vais regarder de mon côté.

**Comment by Portekoi** [comment]
C'est effectivement le cas. Je regarde.

**Comment by Portekoi** [comment]
J'ai trouvé. Je livre en début d'après midi.

**Comment by Portekoi** [comment]
Je viens de livrer mais j'ai une erreur quand je me déconnecte, uniquement après une recherche. Je regarde.

**Comment by Portekoi** [comment]
@lgiRomain C'est tout bon !

**Comment by lgiRomain** [comment]
Bonjour Damien, toujours pour ce problème, sur le Dashboard quand on clique sur l'onglet "Commandes" le système coche automatiquement tous les statuts et recherche donc l'ensemble des commandes, ce qui prend un temps considérable.
Avant, le système se souvenait de la l'opération précédente, c'est à dire si nous avions coché uniquement le statut "1ere lecture conforme", en cliquant sur l'onglet "Commandes", le l'onglet "1ere lecture conforme était coché.
Peut-on repartir sur ce fonctionnement?

**Comment by Portekoi** [comment]
J'ai pourtant livré et testé. Je vais revérifier.

**Comment by Portekoi** [comment]
OK c'est après le clic sur "Commande" effectivement. Je regarde

**Comment by Portekoi** [comment]
J'ai corrigé. Je livre.

**Comment by Portekoi** [comment]
C'est en ligne.

**Comment by Portekoi** [comment]
Un CTRL+F sera nécessaire je pense.

**Comment by lgiRomain** [comment]
C'est ok pour nous. Merci
