### ISSUE TITLE
RECOUVREMENT et LETTRAGE inaccessibles The transaction log for database 'Pinard' is full due to 'LOG_BACKUP'.

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#119]
Accès onglets RECOUVREMENT et LETTRAGE "inaccessibles"

Message : The transaction log for database 'Pinard' is full due to 'LOG_BACKUP'.

=> **voir PJ**

On est bloqué en consultation et saisie des paiements

[The transaction log for database 'Pinard' is full due to 'LOG_BACKUP'..pdf](https://github.com/lgi-wines/Extranet-LGI/files/1328378/The.transaction.log.for.database.Pinard.is.full.due.to.LOG_BACKUP.pdf)

**Comment by lgazeau** [comment]
...également bloqué sur tout un tas de fonctionnalités : COPIER-COLLER de fiches produits...
Apparemment le base serait pleine à cause des Sauvegardes.
Merci de votre aide (nettoyage) pour débloquer l'Appli

**Comment by Portekoi** [comment]
C'est nettoyé.
