### ISSUE TITLE
GENERATION AUTOMATIQUE PDF

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#12]
Préalable
1- Dans le formulaire KartID supprimer tag "validé par embouteilleur"
2- "Prête à partir" => "prête à partir théorique" (+2 jours)
3- "Prête à partir" => "prête à partir validé" champ ouvert saisie Philippe, modif possible ADV.

1/ FACTURE
au statut "Facturée" => Génération automatique de la FACTURE au format PDF + envoi manuel par e-mail avec A/R => panier suivi accusé réception. cc : lgi-orders@lgi-wines.com
- Archivage d'une copie de cette facture dans notre Cloud / ADV / Factures 2016
  Libellé de cette facture  : Invoice N° Kart ID N° Réf commande Client 
  Paramétrage de cet envoi au niveau du client (oui par défaut)

2/ PACKING LIST => au statut "Facturée" => Génération automatique de la PACKING LIST au format PDF + envoi manuel par e-mail
cc : lgi-logistics@lgi-wines.com
Paramétrage de cet envoi au niveau de l'adresse de livraison - pays de livraison du client (oui par défaut)

3/ CONF. TRANSPORTEUR (TRANS) : Génération automatique de la confirmation au format PDF + envoi manuel par e-mail 
cc : lgi-logistics@lgi-wines.com

4/ CONF. TRANSPORTEUR (CLIENT) : doc à supprimer

**Comment by MamboJoel** [comment]
Ok. J'ai ce développement en tête depuis notre venue le mois dernier. Merci de l'avoir remonté ici.

**Comment by josneaulgi** [comment]
Bonjour Nicolas,
j'ai lu que le bon de commande de Celine en format PDF était ok, tu peux donc t'attaquer à nos demandes ADV.
Merci de me tenir informée des avancées

**Comment by josneaulgi** [comment]
Est-ce que tu as pu avancer?

**Comment by josneaulgi** [comment]
la génération de la facture au format PDF devient urgent car on ne peut pas avancer si ca ne marche pas. Merci de te pencher dessus.

**Comment by josneaulgi** [comment]
RELANCE

**Comment by MamboJoel** [comment]
On a publié le développement.
Chacun des documents que vous souhaitez passer en PDF fait donc l'objet d'un nouvel onglet. Par exemple "Facture PDF".
Et l'on va retirer les onglets précédents.

**Comment by MamboJoel** [comment]
J'ai remis les onglets précédents.

@Portekoi : @josneaulgi va revenir avec quelques demandes de présentation concernant les pdf générés.

**Comment by MamboJoel** [comment]
@Portekoi  : @josneaulgi remonte par téléphone qu'on ne peut plus retirer le tampon de la facture aspx. J'ai vu que tu avais retiré le javascript. Peux-tu rétablir la fonctionnalité ?

**Comment by MamboJoel** [comment]
@Portekoi j'ai remis les js sur Invoice.aspx. Je suppose que tu les avais retirés sciemment, certainement pour la génération du pdf. J'ai vérifié, celui-ci semble toujours se générer correctement.

**Comment by josneaulgi** [comment]
merci de nous remettre les onglets d'avant correctement, avec la bonne mise en page.
pour les factures : la largeur des colonnes ne vont pas. Trop large pour le type, quty cs, bt./cs, Qty Bt. et pas assez large pour la colonne product.
je reviendrai vers vous pour la mise en page des formats PDF.

**Comment by josneaulgi** [comment]
RELANCE URGENT !!!

**Comment by josneaulgi** [comment]
dans la facture (toujours version pas pdf), l'encadré du n° de facture ne prend pas tout le numéro.

**Comment by Portekoi** [comment]
@MamboJoel J'ai pas la main : tu peux remettre la version de Web/Kart/TransportBill.aspx  et Web/Kart/Invoice.aspx ?

**Comment by MamboJoel** [comment]
@josneaulgi tu peux nous passer un KartID où le document pose problème ?

**Comment by josneaulgi** [comment]
32217

**Comment by Portekoi** [comment]
@josneaulgi J'ai corrigé les colonnes et le numéro de facture qui sortait du cadre, PDF et non PDF.
Pouvez-vous regarder et me dire? Merci

**Comment by MamboJoel** [comment]
@Portekoi j'ai redimensionné les pourcentage de colonne. Synchronise le repository avant de travailler.
Concernant la 32217, on obtient forcément deux pages :

Ancienne facture ASPX :

![image](https://cloud.githubusercontent.com/assets/3832009/24614219/e426f4a6-188a-11e7-9a39-f083905d8ff2.png)

Nouvelle facture ASPX :

![image](https://cloud.githubusercontent.com/assets/3832009/24614252/feb4ce2e-188a-11e7-8f5e-2add3f2cec23.png)

Ancienne facture transformée en PDF :

![image](https://cloud.githubusercontent.com/assets/3832009/24614280/188692ec-188b-11e7-8b5a-6a5b54576cb0.png)

Nouvelle facture transformée en PDF :

![image](https://cloud.githubusercontent.com/assets/3832009/24614303/2624fcd6-188b-11e7-82f1-31940c24fcd9.png)

**Comment by josneaulgi** [comment]
C'est ok pour les non PDF. 
Pour les PDFs, la packing list n'est pas bien mise en page. LGI 32217. Faire pareil que le non PDF.
Pour les PDFs, on est d'accord que le but final est que quand on passe en statut "FACTURE", les PDFs se mettent automatiquement dans le Cloud ?

**Comment by josneaulgi** [comment]
Urgent !! la carrier confirmation non PDF n'a pas la bonne mise en page ! C'est illisible ! 
On peut supprimer les onglets Conf. Transporteur (Client) PDF et non PDF. On garde seulement Conf. Transporteur (trans).

**Comment by Portekoi** [comment]
Bonjour,
Je viens de remettre l'ancienne version en ligne. Cela impactera la version PDF.
Merci de me préciser ce qui était erroné sur la version PDF. 

*Quelles sont les obligations à respecter ?*

Merci

**Comment by Portekoi** [comment]
Ancienne version :
[TransportBill-Avant.pdf](https://github.com/lgi-wines/Extranet-LGI/files/892411/TransportBill-Avant.pdf)

Nouvelle version :
[TransportBill-Apres.pdf](https://github.com/lgi-wines/Extranet-LGI/files/892413/TransportBill-Apres.pdf)

Cela vous aidera à m'en dire plus. Merci

**Comment by josneaulgi** [comment]
URGENT : la mise en page n'est pas totalement identique à l'ancienne version car l'encart de l'adresse de facturation ne rentre plus correctement dans la fenêtre de l'enveloppe.. on est donc obligé de faire un pliage bizzarroïde pour que ça rentre correctement

**Comment by Portekoi** [comment]
@josneaulgi On parle bien de la mise en page pour les factures?

**Comment by Portekoi** [comment]
C'est corrigé. 
![20170410_104738](https://cloud.githubusercontent.com/assets/1560754/24853649/125ce6cc-1ddc-11e7-96b2-8c9669ed1d98.jpg)

**Comment by Portekoi** [comment]
@josneaulgi Vous pouvez me valider les modifications? Merci

**Comment by MamboJoel** [comment]
@josneaulgi nous considérons ce développement clos.

**Comment by Portekoi** [comment]
Voir exemple pour Transport ci-joint pour validation. @josneaulgi 
[Uploading LGI_Kart_TransportBill_31278.pdf…]()
