### ISSUE TITLE
URGENT Problème nom du client

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#125]
bonjour,
les noms des clients ne s'affichent plus normalement.
Ex : http://lgivm.waybis.com/Client/Form.aspx?ClientID=217

sarl-le-verre-gourmand

tout est en minuscule et il y a des "-" entre les mots

**Comment by MamboJoel** [comment]
Ok je regarde.

**Comment by MamboJoel** [comment]
On les a rétablis.
