### ISSUE TITLE
Problème n° chrono commandes

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#126]
on est du n° de PO LGI 35319 à  LGI 36318, pourquoi ?

**Comment by MamboJoel** [comment]
C'est à cause d'une panne du serveur SQL ayant eu lieu hier. Nous avons pris contact avec l'hébergeur, AMD.
Plus d'infos là : https://stackoverflow.com/questions/14146148/identity-increment-is-jumping-in-sql-server-database
