### ISSUE TITLE
TOUJOURS PROBLEME NOM CLIENT

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#127]
Nicolas,
ne clotûres pas stp mes issues, je le fais quand j'ai vérifié.
Car là, toujours le souci !

http://lgivm.waybis.com/Client/Form.aspx?ClientID=1189

**Comment by MamboJoel** [comment]
Les 79 derniers clients créés n'avaient pas été traités. On les a restitués.
D'accord pour la clôture des issues, on a le reflex de fermer à la place de l'utilisateur car ceux comme toi qui le font sont extrêmement rares et des issues résolues s'entassent et nourrissent la confusion au sein du projet en se mêlant à des problèmes non résolus.
Cela dit, je me demande, lorsqu'elle est cloturée, tes droits te donnent pas la possibilité de la rouvrir ?
![image](https://user-images.githubusercontent.com/3832009/31718433-3b4b7740-b410-11e7-9cad-4cb19ab72c89.png)

**Comment by josneaulgi** [comment]
Non, je n'ai pas les droits pour ré-ouvrir.

**Comment by MamboJoel** [comment]
D'accord. Je t'ai attribué le rôle `admin` sur https://github.com/lgi-wines
Tu me confirmes en fermant / réouvrant. (Et en fermant si cette issue est résolue.)

**Comment by josneaulgi** [comment]
ok ça marche ! Merci Nicolas
