### ISSUE TITLE
Problème nom client toujours

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#128]
il y a une partie du nom qui a disparu.
http://lgivm.waybis.com/Client/Form.aspx?ClientID=1189
Ex : CONVIVIALITY
C'était CONVIVIALITY GROUP LTD

je n'ai pas re-issuer car je ne l'ai pas trouvé. Quand les issues sont closed, où puis-je les retrouver ?
Merci

**Comment by MamboJoel** [comment]
![image](https://user-images.githubusercontent.com/3832009/31722606-d4637764-b41c-11e7-8c31-a0ea7f7121b9.png)

On va récupérer un dump de la base. Dans l'intervalle vous pouvez changer le nom.

**Comment by MamboJoel** [comment]
On a récupéré le dump. A priori l'écrasante majorité des clients devraient être rétablis. Dis-moi si t'as le sentiment que plus d'1% des clients posent problème.

**Comment by josneaulgi** [comment]
OK
