### ISSUE TITLE
Gestion de la VM et des routines planifiées

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#134]
On a des problèmes sur cette nouvelle VM avec la routine nocturne "nightroutine" et la routine "updatetableau". 
- Elles lèvent des `Timeout`.
- On voit des pools d'application arrêtés par IIS.

**Comment by MamboJoel** [comment]
@meillere on a des problèmes de timeout avec le peuplement notamment de la table `BDW_OrderItem`. Est-ce que cette table est encore utilisée par les outils Access que tu maintiens ? @lgazeau tu sais peut-être ? Je sais que le projet `Biz` est obsolète, cette table l'est-elle aussi ?

**Comment by Portekoi** [comment]
De ce que je constate factuellement : 

1. Des attaques SQL ont  lieu 33 fois par minute (voir image ci-dessous)
1. Deux tâches planifiées s'exécutent et semblent faire le job (notamment Night Routine qui mouvemente les stocks par rapport aux mises produites) mais se terminent sur une erreur `kernelbase`
1. Les pools d'applications tombent de plus en plus souvent ce qui occasionne une panne totale des sites LGI (Appo / Waybis)
1. les erreurs dans le journal ne remontent parfois plus du tout

Ce phénomène s'est produit ce soir. Impossible de redémarrer les pools jusqu'à ce que je redémarre le service `Journaux et alerte de performance` en le positionnant en automatique comme l'explique `Jarred` ici : 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/2556a86b-f82e-4efb-bcdd-19919facbff6/application-error-faulting-module-name-kernelbasedll-version-61760016385?forum=vcgeneral

*Ce que je pense (mais je peux me tromper)*
Les logs sont sur-sollicité de part les attaques SQL que nous subissons. Du coup, quand un programme essaie d'écrire dans le journal de Windows qui est déjà bien occupé, il lève une erreur `kernelbase` ou n'écrit pas du tout (C'était le cas ce soir). Cela se produit pour les pools de IIS : dès qu'ils veulent écrire dans ce journal, ils s'arrêtent en erreur. 
MAIS : cela peut aussi venir des deux tâches qui,  pour une raison dont seul Windows en a le secret, plombe le service `Journaux et alerte de performance`

*Comment avancer?*
Il faut **absolument** régler le problème des attaques SQL qui de toutes manières, menacent le serveur.
Une fois ce premier danger écarté, nous pourrons nous concentrer sur les 2 jobs si le problème persiste.

![image](https://user-images.githubusercontent.com/1560754/32299363-a8ed575a-bf55-11e7-89ad-2c71beeb12f2.png)

**Comment by MamboJoel** [comment]
Je me pose la même question, @meillere , à propos de la table `Component_Datawarehouse` : est-elle encore utilisée ?

**Comment by MamboJoel** [comment]
Je confirme. 

- J'ai débogué les deux routines en réusinant certaines requêtes et en désactivant certains services qui me semblent clairement obsolètes. Mais je demande la confirmation de @meillere . Le cas échéant je les retravaillerai.
- Cette machine est [attaquée sans arrêt](https://github.com/lgi-wines/Extranet-LGI/issues/130), n'est pas en l'état un environnement sain de déploiement. On insiste sur ce problème et je propose à nouveau la mise ne place d'un firewall : le serveur hébergeant l'application auparavant était derrière un firewall et son usage n'en était pas grévé.

**Comment by MamboJoel** [comment]
@Portekoi oui je veux bien que tu te penches sur la relocalisation des routines or `inetpub`. Je les ai déplacées dans `C:\PinardRoutines` et lancé leur traitement via le planificateur de tâche et elles semblent ne jamais s'arrêter :

![image](https://user-images.githubusercontent.com/3832009/32301480-57d318b0-bf5e-11e7-9152-7aa8a17ce532.png)

Or, en les lançant via `cmd` elles fonctionnent bien et rapidement.

**Comment by Portekoi** [comment]
Ton paramétrage me semble bon. En faisant F5, on voit que les tâches s'arrêtent.

**Comment by Portekoi** [comment]
Les batchs sont passés et ils ont terminé en erreur mais les pools ne semblent pas avoir été affectés. A surveiller.

**Comment by MamboJoel** [comment]
T'as le compte rendu des erreurs ? Je voudrais quand même régler ça.

**Comment by Portekoi** [comment]
Rien dans les journaux depuis 23h18. j'ai beau actualiser mais rien à faire. 

![image](https://user-images.githubusercontent.com/1560754/32301974-952002e4-bf60-11e7-8591-83cf252dc304.png)

**Comment by Portekoi** [comment]
Rien à part le plantage aussi d'un plan de sauvegarde. Je regarde d'où ça vient.

![image](https://user-images.githubusercontent.com/1560754/32302226-e34c90c6-bf61-11e7-92ec-cada5b0b7cbb.png)

**Comment by MamboJoel** [comment]
Cool. Tu peux te concentrer sur le plan de sauvegarde. Je suis en train de régler le problème de la planification des routines. Pour l'essentielle je supprime les planifications et les recrée.

**Comment by Portekoi** [comment]
Dès que l'on ouvre SQL Serveur depuis le serveur lui même, c'est super super super lent.

**Comment by MamboJoel** [comment]
Oui j'ai constaté ça plusieurs fois. En plus d'être particulièrement inquiétant c'est gênant pour nous car avec nos clients sur nos machines on a peu de droits et il nous faut passer par TSE pour, par exemple, créer une base, une table...

**Comment by Portekoi** [comment]
Alors : sur le plan de maintenance, 9 étapes dont les 6 et 8 qui semblent générer des erreurs.

![image](https://user-images.githubusercontent.com/1560754/32303716-8ca9ae1c-bf6a-11e7-80fc-dd4fb2b5b36d.png)

La sauvegarde n'a pas eu lieu le 2/11 à minuit.
![image](https://user-images.githubusercontent.com/1560754/32303737-b368ef68-bf6a-11e7-9b52-7bdaa34c5bc2.png)

J'ai donc relancé manuellement : 
![image](https://user-images.githubusercontent.com/1560754/32303967-2d2a7c26-bf6c-11e7-854f-9fbdd0aae9cf.png)

Et c'est passé sans erreur : 
![image](https://user-images.githubusercontent.com/1560754/32303983-5e9bcd8c-bf6c-11e7-9d51-b2ee20c47077.png)

Tant que l'on aura autant d'erreurs, on ne pourra pas en avoir le coeur net sur les causes de ces comportements.

**Comment by meillere** [comment]
je n'ai pas ces tables dans le reporting et BWD_orderitem est une table très récente.
Elles sont forcément renseignées par l'application.

**Comment by Portekoi** [comment]
Sauvegardes et processus ok ce matin. Beaucoup moins d'erreurs dans le journal des évènements.
