### ISSUE TITLE
Routine MAJ table Tableau est désactivée

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#136]
La routine de MAJ (toutes les 5 mn ou 30 mn ?) de la _table_ **Tableau** est désactivée.

J'ai fait une MAJ manuelle en cliquant sur le bouton "**Update Tableau**" de l'onglet Reporting de l'Appli (navigation haute), mais il faudrait réactiver la routine de MAJ auto toutes les 5 mn.

D'avance merci.

**Comment by Portekoi** [comment]
De mémoire, elle se chargeait effectivement toutes les 30 minutes mais à partir de 17h30. 

Est-ce vraiment nécessaire qu'il y est une mise à jour toutes les 5 minutes? J'ai peur que cela ne nuise au serveur...

@MamboJoel tu as désactivé des parties de ce chargement non?

**Comment by MamboJoel** [comment]
Oui, je l'ai entièrement réusinée et elle consomme beaucoup moins de proc. Tu peux la passer toutes les 5 minutes.

**Comment by lgazeau** [comment]
Oui, il nous faut "toutes les 5 mn" pour les MAJ liées aux opérations de Fin de Mois.

MERCI d'avance.

**Comment by Portekoi** [comment]
OK je comprends mieux.

J'ai modifié sa planification pour la faire tourner du lundi au vendredi, de 8h00 à 18h00.

Est ce que cela convient ?

**Comment by lgazeau** [comment]
C'est parfait.

**Comment by lgazeau** [comment]
Sauf qu'à l'instant T la table Tableau est "vide"
Dois-je faire un update manuel ?
Peux-tu vérifier la routine ?

**Comment by Portekoi** [comment]
Elle a planté. Je regarde dans le journal des évènement.

![image](https://user-images.githubusercontent.com/1560754/32385275-e03f5d98-c0bd-11e7-893c-eee8ee40da75.png)

**Comment by Portekoi** [comment]
Je viens de la relancer à la main et elle est passée.

**Comment by lgazeau** [comment]
C'est OK
Mais il faut que la MAJ auto s’exécute convenablement toutes les 5 mn

**Comment by Portekoi** [comment]
Oui je me doute. 

@MamboJoel : Exception SQL mais quand je la lance manuellement, ça passe... bizarre : 

```

Informations sur l'exception : System.Data.SqlClient.SqlException
   à System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1<System.Action>)
   à System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, Boolean, Boolean)
   à System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, Boolean ByRef)
   à System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, System.String, Boolean, Boolean)
   à System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, Boolean, Int32, System.Threading.Tasks.Task ByRef, Boolean, Boolean, System.Data.SqlClient.SqlDataReader, Boolean)
   à System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, System.String, System.Threading.Tasks.TaskCompletionSource`1<System.Object>, Int32, System.Threading.Tasks.Task ByRef, Boolean ByRef, Boolean, Boolean)
   à System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(System.Threading.Tasks.TaskCompletionSource`1<System.Object>, System.String, Boolean, Int32, Boolean ByRef, Boolean, Boolean)
   à System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   à Waybis.Framework.EntityManager.RunQuery(Waybis.Framework.Query)
   à Waybis.Pinard.Application.UpdateTDB(System.DateTime, System.DateTime)
   à Waybis.Pinard.DataTransfers.Module1.DoIt()
   à Waybis.Pinard.DataTransfers.Module1.Main()

```

**Comment by Portekoi** [comment]
Bon, elle vient de passer sans planter, toute seule à l'instant. A suivre.

**Comment by lgazeau** [comment]
OK A SUIVRE

**Comment by Portekoi** [comment]
Cela ne changera quasiment rient mais j'ai remplacé le `Delete` par un `Truncate` dans la procédure `UpdateTableau`

Soit : `truncate table [Pinard].[dbo].[Tableau]`

J'ai toujours entendu dire que c'était plus rapide mais je ne sais pas si c'est toujours d'actualité.
https://stackoverflow.com/questions/139630/whats-the-difference-between-truncate-and-delete-in-sql

Et j'ai planifié la tâche toutes les 5 minutes.

**Comment by MamboJoel** [comment]
Laurent remonte toujours des problèmes avec la planification. Il constate l'anomalie car la table "tableau" est vide.

- Dans l'observateur d'événements je constate une erreur non managée :

```
Récipient d’erreurs , type 0
Nom d’événement : CLR20r3
Réponse : Non disponible
ID de CAB : 0

Signature du problème : 
P1 : Waybis.Pinard.DataTransfers.exe
P2 : 1.0.0.0
P3 : 5a05941b
P4 : System.Data
P5 : 4.7.2102.0
P6 : 59371adb
P7 : 1d3b
P8 : 27
P9 : System.Data.SqlClient.Sql
P10 : 

Fichiers joints :

Ces fichiers sont peut-être disponibles ici :
C:\Users\admin-ntlm\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Waybis.Pinard.Da_196d8e145326094e260158cf8b2b537c6aa687_7f75c1cf_d68ed02b

Symbole d’analyse : 
Nouvelle recherche de la solution : 0
ID de rapport : d37a444c-d359-11e7-80e8-005056a1f3c2
Statut du rapport : 2048
Récipient avec hachage : 
```

Elle est très vague sauf la mention de `System.Data.SqlClient.sql`. Le fichier AppCrash n'apporte rien.

Quand je lance la routine à la main tout fonctionne correctement. Le planificateur aussi fonctionne.
Il semblerait que ce soit un bogue furtif. @lgazeau à quelle fréquence le constates-tu ?

**Comment by lgazeau** [comment]
De nouveau "Tableau" était vide => pas de MAJ des vieux outils Reporting (.xls, Access et Appli).
Je viens de faire une MAJ "manuelle" via le bouton "Update Tableau" de l'onglet REPORTING de l'Appli.
C'est OK, mais c'est problématique car c'est fréquent.
Merci de regarder pour solutionner ce pb.

**Comment by Portekoi** [comment]
J'ai reçu un mail d'erreur au niveau de la connexion SQL.  J'ai modifié en ajoutant ceci à la tâche : 

![image](https://user-images.githubusercontent.com/1560754/33664589-7880050e-da94-11e7-9c4e-0ce27e4b22cf.png)

**Comment by Portekoi** [comment]
Si ça marche pas, on fera ceci : 
https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

**Comment by Portekoi** [comment]
La routine ayant planté ce matin à 8h00, je suis intervenu pour enlever le message d'erreur windows.

Je viens de suivre le tuto sur le lien dans mon commentaire précédent en espérant que cela règle définitivement le problème.

**Comment by Portekoi** [comment]
La routine a planté ce matin à 9h00 mais c'est bien exécutée à 9h05. Je pense que le problème est réglé.

**Comment by Portekoi** [comment]
Je pense que ma dernière modification a réglé le souci d'arrêt de cette tâche lors d'une erreur.
