### ISSUE TITLE
urgent pas possible de saisir une commande

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#138]
bonjour,
je n'arrive pas à saisir une commande. 
http://lgivm.waybis.com/Client/ProductList.aspx?ClientID=791

voici le message

Erreur du serveur dans l'application '/'.

La référence d'objet n'est pas définie à une instance d'un objet.

Description : Une exception non gérée s'est produite au moment de l'exécution de la requête Web actuelle. Contrôlez la trace de la pile pour plus d'informations sur l'erreur et son origine dans le code. 

Détails de l'exception: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.

Erreur source:

**Comment by Portekoi** [comment]
Bonjour,

Et en te déconnectant et reconnectant? Cela le fait sur tous les produits?

**Comment by Portekoi** [comment]
Je viens de tester et j'ai créé le KartID : `36926`

**Comment by josneaulgi** [comment]
j'ai 7 produits sur la commande ! pas le temps de vérifier sur chaque produit. 
Merci de me dire

**Comment by josneaulgi** [comment]
qu'est ce qui peut bloquer?

**Comment by Portekoi** [comment]
Sans plus d'éléments, cela va être compliqué. 7 produits => Lesquels?

**Comment by josneaulgi** [comment]
c'est bon ca marche
