### ISSUE TITLE
Changement de LOGO / Font

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Extranet-LGI#140]
[logos-lgi.zip](https://github.com/lgi-wines/Extranet-LGI/files/1521299/logos-lgi.zip)
```
Nous venons de modifier notre charte graphique LGI.

Peux-tu modifier notre logo sur :

*Waybis V1
*Waybis V2
*Appro
*Supports générés automatiquement par Waybis :
    *Factures
    *Bon de commande
    *Planning…

En pj le nouveau logo sous différents formats.

Idéalement il faudrait changer les polices et les couleurs des supports envoyés aux clients/fournisseurs, est-ce possible ?

Ci-joint le récap des polices et couleurs, si ok pour toi je t’enverrai un fichier séparé avec les polices.
```

**Comment by Portekoi** [comment]
Je regarde demain pour les documents.

![image](https://user-images.githubusercontent.com/1560754/33479991-7fa10940-d68f-11e7-97f1-9a6078bb8ca4.png)

**Comment by Portekoi** [comment]
J'ai mis en place le nouveau logo utilisé dans les documents (Factures / PackingList etc.)

**Comment by Portekoi** [comment]
@celinelgi Peux tu m'envoyer les polices et la liste des documents à impacter par ces dernières? 

Tu évoques des couleurs dans les supports : peux tu me fournir les liens vers ces derniers que je n'en oublie pas? Merci

**Comment by celinelgi** [comment]
Salut Damien,
Je n'ai pas la liste de l'ensemble des docs concernés, peut-être @lgazeau ?
Ce qui est certain c'est que au niveau des Approvisionnements il y a le Bon de Commande en PDF

Ci-après les référentiels couleurs  et polices je te fais un mail séparé avec les polices car Github ne veut pas les prendre
[Guide_utilisation_COULEURS.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1521670/Guide_utilisation_COULEURS.pdf)
[Guide_utilisation_POLICES.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1521671/Guide_utilisation_POLICES.pdf)

**Comment by Portekoi** [comment]
Ok Merci. Je les ajoute.
[policeschartegraphiquelgi.zip](https://github.com/lgi-wines/Extranet-LGI/files/1521801/policeschartegraphiquelgi.zip)

Pour que je comprenne bien la demande : Au niveau d'un document comme le bon de commande, je vais devoir prendre la police `STAG` sauf pour le titre tout en haut. 

Mais cela risque de faire bizarre si je mélange les polices.

**Comment by lgazeau** [comment]
Le logo de la page d'accueil de l'Appli, en haut à gauche,  n'est pas encore modifié.

**Comment by Portekoi** [comment]
Il faut vider le cache :)

CTRL+F5

**Comment by lgazeau** [comment]
Ca ne fonctionne pas sur mon poste.

**Comment by lgazeau** [comment]
CTRL + F5 ne fonctionne pas sur mon poste.

**Comment by Portekoi** [comment]
Tu es bien sur http://lgivm.waybis.com/ ? Et en navigation privée?
CTRL + SHIFT + P sous Firefox
CTRL + SHIFT + N sous Chrome

**Comment by lgazeau** [comment]
Je suis bien sur http://lgivm.waybis.com/ 

mais pas en navigation privée

Et, en navigation privée, je perds mes codes

**Comment by Portekoi** [comment]
Je pense que c'est un problème de cache uniquement.

**Comment by lgazeau** [comment]
OK

Je veux bien que tu m'appelles lundi pour régler ce... petit problème d'affichage, en me montrant comment vider ce cache

**Comment by Portekoi** [comment]
Ca marche.

**Comment by celinelgi** [comment]
De mon côté ça a marché du premier coup par contre ça n’apparaît toujours pas sur le bon de commande des Approvisionnements

**Comment by Portekoi** [comment]
C'est normal : les bons de commande sont générés à la sauvegarde du `Kart` de mémoire. Cela signifie que le PDF existait déjà avant que change le logo. 

Pour les prochains documents / commandes, cela sera bon.

**Comment by Portekoi** [comment]
Est-il toujours d'actualité de changer aussi les polices sur les éditiques tout en sachant que cela peut avoir des conséquences négatives sur les actuels documents?

**Comment by celinelgi** [comment]
Non pas besoin de changer les polices.
Merci
