### ISSUE TITLE
Visusliasion MISES "déjà produites"

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#141]
L'onglet "Mises" de la navigation haute de l'Appli ne nous donne accès qu'aux  
* Mises planifiées en attente de production
* Mises à planifier
* Mises à venir ayant un défaut de stock
* Récapitulatif produits en stock et à fabriquer

Avons besoin de pouvoir visualiser également les "**Mises déjà produites**" (Ex. : 192738)
C'est urgent car, comme expliqué, nous gérons et assumons (financièrement) désormais des stocks déportés (hors UCC) de composants (Bouteilles, Etiquettess...) et de produits finis chez l'embouteilleur ALLIANCE TERROIRS
Avons besoin de ces infos pour boucler notre fin de mois "comptable" de Novembre 2017

**Comment by Portekoi** [comment]
J'ai commencé à faire des modifications mais je n'accède plus au serveur SQL. Je viens de demander l'autorisation pour pouvoir avancer là dessus.

**Comment by Portekoi** [comment]
Si je ne dis pas de bêtises, vous pouvez avoir ces informations ainsi : 
![image](https://user-images.githubusercontent.com/1560754/33693537-becc8532-daf3-11e7-9b49-404c0af36951.png)

**Comment by lgazeau** [comment]
OK mais cela ne fonctionne pas
Voir Mise N° 192738 pour ALLIANCE TERROIRS => Rien en sort

**Comment by Portekoi** [comment]
Quand je fais la recherche, j'ai bien la mise mentionnée tout en bas : 

![image](https://user-images.githubusercontent.com/1560754/33709005-5480acaa-db3c-11e7-934a-4a0ef56f56f4.png)

Appelle moi pour que je comprenne mieux le souci.
