### ISSUE TITLE
URGENT - Impossible d'accéder à la commande n°99864 sur le système d'appro étiquettes

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#143]
Message d'erreur "[object ProgressEvent]" quand on essaye d'accéder à la commande 99864 sur le système d'appro d'étiquette

**Comment by Portekoi** [comment]
Je regarde

**Comment by Portekoi** [comment]
Dans la base, je vois une incohérence : Le `Label`.`Increment` contient la valeur `OUI` au lieu d'un nombre

![image](https://user-images.githubusercontent.com/1560754/34043993-965416d6-e1a3-11e7-9459-5205b2a83d9a.png)

**Comment by Portekoi** [comment]
Dans cet écran, il faut corriger le `OUI` par le bon chiffre (ou vide) : 

lgivm.waybis.com/Component/Form.aspx?ComponentID=29227

![image](https://user-images.githubusercontent.com/1560754/34044214-5da9ae44-e1a4-11e7-9ae4-6963b04b3474.png)

**Comment by Portekoi** [comment]
Je viens de corriger en mettant `1` pour être certain de corriger l'anomalie et cela fonctionne maintenant.

Je vous laisse voir pour la bonne valeur dans ce champ.

**Comment by Portekoi** [comment]
Je clos.
