### ISSUE TITLE
URGENT PAS POSSIBLE DE FACTURER

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#144]
la Kart ID 37209 car le système dit:

L'entrepôt CHATEAU GRAND MOULIN n'a pas de propriétaire. Veuillez le définir dans l'onglet formulaire.
http://lgivm.waybis.com/Kart/Form.aspx?KartID=37209

merci de régler ce bug pour que nous puissions facturer

**Comment by Portekoi** [comment]
Je pense que c'est parce qu'il y en a 3 et que l'un d'eux n'a pas de propriétaire : 

![image](https://user-images.githubusercontent.com/1560754/34251475-8ccebcaa-e640-11e7-9497-e60d69f2888d.png)

Vous devriez les renommer  pour retrouver le bon dans le menu déroulant.

**Comment by josneaulgi** [comment]
Où est-ce que tu en vois 3 ? Car moi je n'en vois qu'un

**Comment by Portekoi** [comment]
Ici : http://lgivm.waybis.com/Warehouse/List.aspx

**Comment by Portekoi** [comment]
Je vois que tu as réussi à facturer. Je clos cette issue.
