### ISSUE TITLE
Compléter Table dbo_Comptes // Créer Activité 19 "Pris sur Stock LAOZUOFANG"

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#145]
Merci de :
• **Compléter la table dbo_Comptes avec les ID 130 et 131 (cf. PJ)
• Créer dans l’Application l’ Activité 19 "Pris sur Stock LAOZUOFANG"**

[dbo.Comptes 03 01 18.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1600157/dbo.Comptes.03.01.18.xlsx)

Et merci de vérifier que l'utilisation de l'Activité 19 "Pris sur Stock LAOZUOFANG" ne génère aucune écriture dans la journal des ACHATS que génère Jacques 
[dbo.Activity 03 01 18.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1600161/dbo.Activity.03.01.18.xlsx)

**Comment by lgazeau** [comment]
Pouvez-vous m'avancer cette entrée, pour mes arrêtés au 31 12 17

Merci de :
• Compléter la table dbo_Comptes avec les ID 130 et 131 (cf. PJ)
• Créer dans l’Application l’ Activité 19 "Pris sur Stock LAOZUOFANG"

[dbo.Activity.03.01.18.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1606275/dbo.Activity.03.01.18.xlsx)


Et merci de vérifier que l'utilisation de l'Activité 19 "Pris sur Stock LAOZUOFANG" ne génère aucune écriture dans la journal des ACHATS que génère Jacques
dbo.Activity 03 01 18.xlsx
[dbo.Comptes.03.01.18.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1606274/dbo.Comptes.03.01.18.xlsx)

**Comment by MamboJoel** [comment]
@meillere a effectué les modifs souhaitées. Tout est ok pour toi ?

**Comment by lgazeau** [comment]
Les Tables de Jacques sont bien "à jour"

Mais l'Appli n'est pas "à jour'
J'en ai besoin pour boucler ma FDM (Fin de Mois) de Décembre et faire mes Exports ACH et VTE dans la Compta demain à la 1ère heure.
(A l'heure qu'il est, je ne peux pas saisir les paiements avant Ech. car je n'ai toujours pas les factures en COMPTA et dans mon SAGE Treasury).

=> Pas d'accès à l'activité "Pris sur Stock LAOZUOFANG" dans un Kart

Et merci de vérifier que l'utilisation de l'Activité 19 "Pris sur Stock LAOZUOFANG" ne génère aucune écriture dans la journal des ACHATS

**Comment by Portekoi** [comment]
Je ne sais pas comment intervenir là-dessus... Je ne maitrise pas le journal des achats et son alimentation

**Comment by lgazeau** [comment]
Cette entrée a été traitée

On peut fermer cet entrée
