### ISSUE TITLE
Plus Accès Onglet SECURITE "Navigation Haute" Appli

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#147]
Nous n'avons plus d'accès à l'onglet SÉCURITÉ (paramétrage des accès) de la "Navigation Haute" 
 => cf. PJ

Merci de voir le pb et me dire quand c'est OK, car j'ai besoin de modifier des accès.

Bonne journée.

Sincères salutations.
[La référence d'objet n'est pas définie à une instance d'un objet..pdf](https://github.com/lgi-wines/Extranet-LGI/files/1641905/La.reference.d.objet.n.est.pas.definie.a.une.instance.d.un.objet.pdf)

**Comment by Portekoi** [comment]
Un user avait été créé avec tous les champs `null` ce qui a causé l'erreur.
