### ISSUE TITLE
Les imprimeurs ne reçoivent pas systématiquement une alerte mail lorsqu'une commande est passée en "Validée"

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#148]
### Description
Les imprimeurs ne reçoivent pas systématiquement une alerte mail lorsqu'une commande est passée en "Validée", même quand dans leur profil, le statut "validée" est coché dans leur demande d'alerte mail

### Scénario pour reproduire l'anomalie
Ex: commande 100554 => j'ai passé hier soir la commande en statut "Validée" et Almeria PICARD de chez INESSENS m'indique ne pas avoir reçu de mail de passage de statut de cette commande en "validée"

### Résultat attendu
Elle aurait dû recevoir cet email, car le statut "Validée" est coché dans son profil

### Anomalie constatée
Elle n'a pas reçu la validation par mail. Cela n'arrive pas sur toutes les commandes. D'autres imprimeurs m'ont fait part (exceptionnellement) de ce problème

**Comment by Portekoi** [comment]
A-t-elle vérifié son dossier de spam? Il est étonnant que cela fonctionne pour certaines et pas d'autre dans la mesure où le code est le même et que seule, l'adresse mail change.

**Comment by lgiRomain** [comment]
Damien, vu avec l'imprimeur, on laisse le dossier de côté, il se peut que ce problème soit dû à un problème informatique chez l'imprimeur.
Je te tiens informé si le problème se représente

**Comment by Portekoi** [comment]
Ca marche.
