### ISSUE TITLE
Impossibilité Facturer KartID 36971 et 36972

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#149]
Concernant ClientID 1126 "AALBORG - COOP DANMARK"

Impossibilité de facturer KartID 36971 et 36972, alors que KartID 34875 OK 
Possibiïlté d'Editer "Facture proforma" uniquement

Je ne vois pas l'anomalie.
On est déjà tombé sur ce cas de figure, mais je ne retrouve pas l'explication et la solution au bug.

HELP

**Comment by Portekoi** [comment]
Je le vois en facturé le `36971` et `36972` : 
![image](https://user-images.githubusercontent.com/1560754/35405518-af3b4a1a-0206-11e8-938b-b59e4c6b26d4.png)

**Comment by Portekoi** [comment]
PDF Facture pour la `36972` : 

http://lgivm.waybis.com/uploads/Karts/Kart_Invoice_36972_20180125_193411.pdf

**Comment by lgazeau** [comment]
Oui mais tu vois (dans le Doc, et dans le bandeau) du Formulaire que c'est une PRO FORMA
Contrairement au Kart 34875 qui propose bien une vraie FACTURE

**Comment by Portekoi** [comment]
Cela se produit lors que le `Kart` est en état `HasToValidate`.

Ce statut, c'est quand un des produits de la commande est en état `ProductStatus.ToValidate`

Mais je ne vois pas le problème avec le produit pour les deux `Kart` mentionnés.

**Comment by Portekoi** [comment]
https://github.com/lgi-wines/Extranet-LGI/issues/116

**Comment by Portekoi** [comment]
J'hésite à sauvegarder le produit pour voir s'il conserve ce statut...

**Comment by lgazeau** [comment]
Problème identifié
Effectivement le produit souche n'est plus ACTIF, et en plus il a été modifié
A priori on se débrouille

**Comment by Portekoi** [comment]
OK tant mieux. Je n'ai pas trouvé dans le système où visualiser cette information.
