### ISSUE TITLE
N° D'ACCISE

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#15]
Merci de mettre le n° d'accise sur le bon d'achat conditionnement au niveau de l'adresse de livraison. Ex : Kart ID 29691

**Comment by josneaulgi** [comment]
Relance.

**Comment by josneaulgi** [comment]
Est-ce que tu peux stp rajouter le n° d'accise sur le bon d'achat conditionnement au niveau de l'adresse de livraison. Ex : Kart ID 29691

**Comment by MamboJoel** [comment]
Il me faut plus d'information :

- Un lien.
- Le numéro d'accise en question, quoique je peux peut-être le trouver dans un autre document ?

Pour l'instant, avec les éléments que tu me donnes, je vais sur [cette page](http://lgivm.waybis.com/Kart/PurchaseOrder.aspx?exSupplierID=20&KartID=29691) et constate qu'il y a bien un numéro d'accise.

![image](https://cloud.githubusercontent.com/assets/3832009/21267658/902f476a-c3ab-11e6-9aa9-9bd303abf336.png)

**Comment by josneaulgi** [comment]
Bonjour,
le n° d'accise n'y est pas toujours, ça dépend des commandes. Sur les commandes en achat LGI, sur le bon d'achat conditionnement, en adresse de livraison, le n° d'accise du client ne s'y trouve pas. voici le lien : 
http://lgivm.waybis.com/Kart/PurchaseOrder.aspx?exSupplierID=20&KartID=29691
Ce N° d'accise, tu peux le trouver dans le formulaire du client ou sinon sur l'adresse de livraison.
