### ISSUE TITLE
Compléter INCOTERM pas VILLE Départ

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#151]
La notion d' INCOTERM doit être complétée par la VILLE de "Départ"

=> Dans le Formulaire KartID, merci de créer un champs texte (libre/ouvert)
que nous remplirons ou pas

et rajouter ce champs dans la FACTURE, derrière l'INCOTERM
Exemple KartID 36752 
=> on rentre "Cébazan"
=> on récupère sur Facture "EXW_Cébazan"

On ne peut pas l'auto-alimenter par la Ville de l'embouteilleur du Kart, car dans le cas d'un Groupage, c'est le lieu de regroupement (Groupage) qui sera retenu.

**Comment by Portekoi** [comment]
Ajout colonne en test pour le moment. A exécuter en production : 
```sql
Alter Table Pinard.dbo.Kart
Add IncotermCity varchar(75) NULL
```

**Comment by Portekoi** [comment]
Voir exemple PDF en test ci-joint : 
[Kart_Invoice_32428_20180130_175546.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1678590/Kart_Invoice_32428_20180130_175546.pdf)

Au  niveau de l'écran `Kart` : 

![image](https://user-images.githubusercontent.com/1560754/35579547-39e54632-05e7-11e8-9887-ebbde11eacaf.png)

**Comment by lgazeau** [comment]
OK => Mettre en prod

**Comment by Portekoi** [comment]
Je livre ce soir

**Comment by Portekoi** [comment]
C'est en place. J'ai saisi le `Kart` `36752` : 
https://lgivm.ntlm.tech/uploads/Karts/Kart_Invoice_36752_20180130_215958.pdf

**Comment by lgazeau** [comment]
On souhaite finalement l'auto-alimenter "par défaut" avec la Ville de l'embouteilleur du Kart, et dans le cas d'un Groupage l'ADV modifiera avec lieu de regroupement (Groupage) puisqu'il s'agit d'un champ ouvert.
Merci de modifier.

**Comment by Portekoi** [comment]
@lgazeau Je ne vois pas de champ `Groupage` dans le formulaire d'un `Kart`. Pourquoi ne pas utiliser le champ que j'ai ajouté à cet effet `Incoterm Ville` que je garnierais automatiquement lors de la création d'un `Kart` par la ville de l'embouteilleur et que vous pourriez modifier si besoin?

**Comment by lgazeau** [comment]
C'est exactement ce que je voudrais.
J'ai dû être confus dans ma demande initiale.

**Comment by Portekoi** [comment]
Ok, j'ai eu un peu de mal à cause du LifeCycle d'`ASP.Net`.

### A la création d'un Kart 

Dans le champ `IncotermCity`, je mets la ville de l'embouteilleur si cette dernière existe bien.

### A la modification de l'embouteilleur

En cas de modification de l'embouteilleur depuis le `Kart`, je modifie en conséquence le champ `IncotermCity`

### En cas de modification (tout court)

Je ne change pas l'`IncotermCity` sauf si vous le changez manuellement

@lgazeau Est-ce que cela te convient?

**Comment by lgazeau** [comment]
C 'est OK.
A priori on ne peut pas changer l'embouteilleur depuis le Kart, car les fiches produits sont montées par rapport à 1 embouteilleur.

**Comment by Portekoi** [comment]
Ok j'avais vu ce menu mais maintenant que tu le dis, effectivement, cette modification n'est pas nécessaire.

![image](https://user-images.githubusercontent.com/1560754/36156719-2dd1197e-10d8-11e8-8982-61b021b004e8.png)

Donc je modifie à nouveau mon code et je livrerai ce soir.

**Comment by lgazeau** [comment]
OK

**Comment by Portekoi** [comment]
Livré et testé
