### ISSUE TITLE
Interdire Saisie KartID si ClientNumber (Compte Client) non renseigné dans Formulaire Client

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#152]
Merci d'Interdire la Saisie d'une Commande (KartID) si ClientNumber (Compte Client) non renseigné dans Formulaire Client.

=> avec un message expliquant que le **ClientNumber (Compte Client) n'est pas renseigné**

car nous avons trop de problème à l'intégration des VTE quand ce champ est vide.

D'avance merci.

**Comment by MamboJoel** [comment]
@Portekoi je peux te laisser traiter ce cas ?

**Comment by Portekoi** [comment]
Oui je vais m'en occuper.

**Comment by Portekoi** [comment]
Je livre après 18h pour éviter tout problème

![image](https://user-images.githubusercontent.com/1560754/35555947-1e49eedc-05a1-11e8-91ef-60ba28657a9b.png)

**Comment by lgazeau** [comment]
OK

**Comment by Portekoi** [comment]
C'est livré
