### ISSUE TITLE
Pb Création ADRESSE LIVRAISON (Delivery Adress)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#153]
Pour ClientID 1269 "TUESDAY WINE"

ne parvenons pas à créer une Adresse de Livraison => voir PJ

Cannot insert the value NULL into column 'Modified', table 'lgi_people.dbo.Agent'; column does not allow nulls. INSERT fails.
The statement has been terminated.
Description : Une exception non gérée s'est produite au moment de l'exécution de la requête Web actuelle. Contrôlez la trace de la pile pour plus d'informations sur l'erreur et son origine dans le code. 

Détails de l'exception: System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Modified', table 'lgi_people.dbo.Agent'; column does not allow nulls. INSERT fails.
The statement has been terminated.

[Pb Delivery Adress Client ID 1269 Cannot insert the value NULL into colum..._br_The statement has been terminated..pdf](https://github.com/lgi-wines/Extranet-LGI/files/1677419/Pb.Delivery.Adress.Client.ID.1269.Cannot.insert.the.value.NULL.into.colum._br_The.statement.has.been.terminated.pdf)

**Comment by Portekoi** [comment]
@lgazeau Vous pouvez réessayer?

**Comment by lgazeau** [comment]
OK Thanks

**Comment by Portekoi** [comment]
@MamboJoel J'ai mis le champ `Modified` en `nullable` dans la table.
