### ISSUE TITLE
REPORTING : ClientRename => Client ID 603 devient 1136   (TIANJIN)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#154]
Compléter la table ClientRename :

Client ID 603 TIANJIN TEXTILE GROUP IMPORT AND EXPORT INC. devient Client ID 1136

TIANJIN FOODSTUFFS IMP.& EXP. Co., Ltd  PO TIANJIN OTS

Ce serait bien de mettre en place l’interface dans l’application pour modifier ClientRename et la table des Comptes.
Depuis l’oblte paramétrage 
2 accès : 
•	Estelle MUR
•	Laurent GAZEAU

**Comment by Portekoi** [comment]
J'ai mis à jour la table `ClientRename`.

`OldClientID` : `603`
`NewClientID` : `1136`

Je n'ai pas compris pour les accès depuis l'onglet paramétrage.

**Comment by lgazeau** [comment]
OK Thanks
