### ISSUE TITLE
Autorisation Exportateur Agréé COREE NORVEGE GEORGIE UKRAINE CAMEROUN AFSUD SUISSE du 01 02 18

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#156]
Pour tous les Kart ayant comme **Country Delivery Adress** COREE NORVEGE GEORGIE UKRAINE CAMEROUN AFSUD SUISSE, merci de faira apparître la mention sur Facture 👍 

_« The exporter of the product covered by this document (customs authorization n° FR 003480/0194) declares that except where otherwise clearly indicated, this product is of European Union preferential origin »
« L’exportateur des produits couverts par le présent document : autorisation douanière N° FR 003480/0194 déclare que, sauf indication claire du contraire, ces produits ont l’ORIGINE préférentielle de l’Union Européenne »_

cf. PJ avec Exemple KartID 37 819 pour "Ernest Wine" en COREE

[KartID 37819 COREE Ernest Wine.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1711261/KartID.37819.COREE.Ernest.Wine.pdf)

[Mention sur Facture Autorisation Exportateur Agréé COREE NORVEGE GEORGIE UKRAINE CAMEROUN AFSUD SUISSE du 01 02 18.docx](https://github.com/lgi-wines/Extranet-LGI/files/1711252/Mention.sur.Facture.Autorisation.Exportateur.Agree.COREE.NORVEGE.GEORGIE.UKRAINE.CAMEROUN.AFSUD.SUISSE.du.01.02.18.docx)

__

**Comment by lgazeau** [comment]
Merci de gérer cette entrée pour ne pas risquer de blocage en DOUANES sur COREE NORVEGE GEORGIE UKRAINE CAMEROUN AFSUD SUISSE

**Comment by Portekoi** [comment]
Je suis déjà dessus.

**Comment by lgazeau** [comment]
Ne te fais pas mal !

**Comment by Portekoi** [comment]
Ce n'est pas super confortable, je le concède ;)

**Comment by Portekoi** [comment]
Exemple en test : 
[Kart_Invoice_32429_20180213_143248.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1720043/Kart_Invoice_32429_20180213_143248.pdf)

Est-ce que c'est bon ainsi?

**Comment by lgazeau** [comment]
That's good
Tu peux mettre en ligne.
Merci

**Comment by Portekoi** [comment]
Je livre en fin de journée pour ne pas vous gêner.

**Comment by Portekoi** [comment]
C'est en production  : https://lgivm.ntlm.tech/uploads/Karts/Kart_Invoice_37819_20180213_225627.pdf
