### ISSUE TITLE
Impossibilité Créer Nouvel Utilisateur à partir onglet "Sécurité"

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#157]
Impossibilité Créer Nouvel Utilisateur (Flora ORIOU) à partir onglet "Sécurité"
=> voir PJ

[La référence d'objet n'est pas définie à une instance d'un objet..pdf](https://github.com/lgi-wines/Extranet-LGI/files/1716091/La.reference.d.objet.n.est.pas.definie.a.une.instance.d.un.objet.pdf)

**Comment by Portekoi** [comment]
@lgazeau 
Je peux avoir un print screen de l'écran avant l'envoi du formulaire? Juste pour voir ce qui a été saisie et si je reproduis le bogue.

**Comment by lgazeau** [comment]
Damien,

Je ne vois pas bien ce que tu me demandes 

En fait, quand je vais avec mon Login (j'ai normalement tous les droits) dans l'onglet "Sécurité" de la navigation haute, je lève l'erreur qui ci-après et en PJ 

[Impression Ecran.docx](https://github.com/lgi-wines/Extranet-LGI/files/1716297/Impression.Ecran.docx)
[La référence d'objet n'est pas définie à une instance d'un objet..pdf](https://github.com/lgi-wines/Extranet-LGI/files/1716298/La.reference.d.objet.n.est.pas.definie.a.une.instance.d.un.objet.pdf)

**Comment by Portekoi** [comment]
Ok, j'ai cru que c'était à la soumission du formulaire pour la création d'un utilisateur. Je pense c'est lié à https://github.com/lgi-wines/Extranet-LGI/issues/147

Je regarde

**Comment by Portekoi** [comment]
@lgazeau Ca devrait être bon.

**Comment by Portekoi** [comment]
Je laisse cette issue ouverte pour voir pourquoi des utilisateurs sont créés avec tous les champs à `null`

**Comment by Portekoi** [comment]
L'erreur persiste. Je regarde.

**Comment by lgazeau** [comment]
Ce n'est pas bon.
Avec mon Login, je me fais virer dès que j'appuie sur l'onglet "Sécurité" dans lequel je veux rentrer pour créer un nouvel utilisateur.

**Comment by Portekoi** [comment]
Oui j'ai vu. Je regarde.

**Comment by Portekoi** [comment]
@lgazeau Je comprends pas : Un `User` avec tous les champs à vide se créé... 

Peux tu aller sur ce lien et me dire si cela fonctionne sans rien faire d'autre? : 
http://lgivm.waybis.com/User/UserList.aspx

**Comment by lgazeau** [comment]
Même erreur
Voir PJ 
['authentication.lgi.ntlm.tech'.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1716361/authentication.lgi.ntlm.tech.pdf)

**Comment by Portekoi** [comment]
Ok, je n'avais pas la même erreur. Je dois relivrer. J'attends 18h15 si pas d'urgence de votre côté.

**Comment by lgazeau** [comment]
OK
J'attends

**Comment by Portekoi** [comment]
Désolé pour le délai. C'est corrigé et livré. Le bogue ne reviendra plus.

**Comment by lgazeau** [comment]
Peux-tu supprimer les utilisateurs "vides" ?
Il faudrait me redonner la main sur la "suppression d'1 utilisateur" (salarié qui quitte l'entreprise)

Sinon, cela semble OK
A SUIVRE

**Comment by Portekoi** [comment]
Fait
