### ISSUE TITLE
Reporting APPLI remonter champ COM_NETTE   - URGENT

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#159]
URGENT  - Dans le REPORTING de l'APPLI, merci de remonter le champ COM_NETTE (qui doit se trouver dans "Tableau")   (cf. PJ)

car nous n'avons que COM_LGI

FYI : COM_NETTE = COM_LGI - BUDGET - PORT

[ReportingAPPLIsortirCOM_NETTE.docx](https://github.com/lgi-wines/Extranet-LGI/files/1727279/ReportingAPPLIsortirCOM_NETTE.docx)

**Comment by Portekoi** [comment]
il faut modifier la procédure stockée `[UpdateTableau]` et ajouter ne colonne dans la table `Tableau`

**Comment by lgazeau** [comment]
OUI,
Merci de faire le nécessaire

**Comment by Portekoi** [comment]
Liste des champs dans la table 

`[D_CDE]
      ,[OLD_PO]
      ,[PO_LGI]
      ,[CLIENT]
      ,[PO_CLIENT]
      ,[PAYS]
      ,[PROD]
      ,[FACT]
      ,[FACT_BTL]
      ,[DEPART]
      ,[MOIS]
      ,[H_TVA]
      ,[CESSION_TOTAL]
      ,[EQUIVALENT_75CL]
      ,[QT_BTLLE]
      ,[QT_VRAC]
      ,[QT_BIB]
      ,[PRDT]
      ,[STYLE]
      ,[FAM]
      ,[MARQUE]
      ,[COULEUR]
      ,[COM_BRUTE]
      ,[COM_AGENT]
      ,[COM_LGI]
      ,[AGENT]
      ,[COM_FF]
      ,[BUDGET]
      ,[EXERCICE]
      ,[CLIENTID]
      ,[TYPE]
      ,[ProductID]
      ,[CLIENT_OLD]
      ,[ProductConditioningID]
      ,[Status]
      ,[InvoiceMode]
      ,[VATLAw]
      ,[VATRate]
      ,[InvoiceNumber]
      ,[MakeId]
      ,[BottlerID]
      ,[VineID]
      ,[AppellationDetailID]
      ,[CA]
      ,[COM_CAVE]
      ,[PurchaseType]
      ,[ImportTag]
      ,[CreationDate]
      ,[ModificationDate]
      ,[ID]
      ,[EQUIV_CS9L]
      ,[EQUIV_L]
      ,[REQ_DTE]
      ,[NBRE]
      ,[CENT]
      ,[OP]
      ,[Millesime]
      ,[Tag]
      ,[PORT]
      ,[KartDetailType]`

**Comment by lgazeau** [comment]
Pourriez-vous me régler ce pb d'affichage dans le REPORTING de l'APPLI, en remontant le champ COM_NETTE (qui doit se trouver dans "Tableau") (cf. PJ) ,
car nous n'avons que COM_LGI
FYI : COM_NETTE = COM_LGI - BUDGET - PORT
[ReportingAPPLIsortirCOM_NETTE.docx](https://github.com/lgi-wines/Extranet-LGI/files/1830198/ReportingAPPLIsortirCOM_NETTE.docx)

**Comment by Portekoi** [comment]
Je m'y essaie ce soir.

**Comment by Portekoi** [comment]
Je pense avoir terminé. A toi de me dire si cela te semble cohérent au niveau des montants.

**Comment by lgazeau** [comment]
PARFAIT
