### ISSUE TITLE
LIASSE DE COMMANDE COURTAGE

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#16]
La liasse de commande sur les commandes Courtage est décalée. Ex: 29637 / http://extranet.lgi-wines.com/Kart/Order.aspx?KartID=29637

**Comment by josneaulgi** [comment]
RELANCE

**Comment by josneaulgi** [comment]
La liasse de commande sur les commandes Courtage est décalée. Ex: 29637 / http://extranet.lgi-wines.com/Kart/Order.aspx?KartID=29637

**Comment by MamboJoel** [comment]
[Le nouveau lien](http://lgivm.waybis.com/Kart/Order.aspx?KartID=29637)

Que faut-il faire alors ? Supprimer la colonne TC LGI ?

**Comment by josneaulgi** [comment]
tout a l'air d'être revenu dans l'ordre. On peut mettre cette issue en statut CLOSED. Tu fais comment?

**Comment by MamboJoel** [comment]
Je t'envoie une invitation pour avoir accès au droit de fermer les issues.
