### ISSUE TITLE
Changement automatique de composants

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#160]
Message original de de Romain MOSTACCHI

> - Remplacer le composant bouchon « Colmate 44x24 2eme / ARTICLE # 4613 » par « Colmate 44x24 2eme Personnalisé Mis en bouteille en France / ARTICLE # 30415 »
> - Remplacer le composant bouteille « BDX CONIQUE Antique - Art 104» par « BDX CONIQUE FM - Art 24213»
> - Remplacer le composant bouteille « BDX ECO L+G Verte a Vis - Art 7159» par « BDX BORIS Verte a Vis - Art 29303»
> - Remplacer le composant bouchon «Colmate 44x24, QUALITE S» par « Colmate 44x24, QUALITE S, personnalisé Mis en bouteille en France »
> - Remplacer le composant bouchon «TWIN TOP 44 mm A - Art 246» par «TWIN TOP 44 mm A - Personnalisé Mis en bouteille en France - Art 30417»

**Comment by Portekoi** [comment]
Je viens de le supprimer et de le rajouter. Il faut qu'il confirme son  inscription en cliquant sur le lien  situé dans le mail.
Je  le contacte par mail pour le lui dire.

**Comment by Portekoi** [comment]
@lgiRomain peux tu répondre à ce commentaire pour tester? Merci.

**Comment by lgiRomain** [comment]
Présent

**Comment by lgiRomain** [comment]
Concernant la demande initiale de cet issue, les changements demandés sont à faire uniquement sur les fiches produits en statut "Actif", "A valider" ou "Projet". Ne pas toucher les produits "Archivés".
Merci

**Comment by Portekoi** [comment]
@MamboJoel Tu peux me confirmer que cette modification est un update dans la table `[Pinard].[dbo].[KartProduct]`, colonne `ProductID` ? J'ai pas trop envie de me planter là dessus... Merci 😉

**Comment by lgiRomain** [comment]
Salut @MamboJoel et @Portekoi , vous avez pu avancer sur cette demande. 
Il faudrait que ce soit fait rapidement car on a déjà commencé physiquement les changements de composant lors des tirages

**Comment by lgiRomain** [comment]
ATTENTION: rappel, il ne faut faire ces changement que sur les fiches produits en statuts "Actifs", "A valider" ou "Projet". Ne pas toucher aux "Archivés"

**Comment by Portekoi** [comment]
Oui, il s'agit des statuts : `[Pinard].[dbo].[Product] / Status in 3, 5, 2`

**Comment by Portekoi** [comment]
@lgiRomain Je viens de faire le changement du premier composant ( `4613` => `30415 ` )

http://lgivm.waybis.com/Product/ComponentList.aspx?ProductID=1690

Avant : 
![image](https://user-images.githubusercontent.com/1560754/36723990-10064c0e-1bb2-11e8-9e4c-542723453a45.png)


Après : 
![image](https://user-images.githubusercontent.com/1560754/36723971-030f0ca2-1bb2-11e8-92d9-91e492642200.png)


Dis moi si tout est bon pour toi.

**Comment by Portekoi** [comment]
```sql

 update prdcpt
	Set prdcpt.ComponentID = 30415 
 From
	[Pinard].[dbo].[ProductComponent] as prdcpt inner join 
	[Pinard].[dbo].[Product] as prd on prdcpt.ProductID = prd.ID
 Where 
		prdcpt.componentId = 4613 
	And 
		prd.Status in (3, 5, 2) 
	And 
		prd.ID = 1690

```

**Comment by lgiRomain** [comment]
Oui c'est bon pour moi, tu peux procéder au reste

**Comment by Portekoi** [comment]
Table sauvegardée sous `ProductComponent.20180227D`

Ok pour tous les produits (1583 en tout) pour le composant `4613`. Je regarde pour les autres.

**Comment by Portekoi** [comment]
Etat des lieux : 

Ok pour :

* Pour le `Component` `4613` : 1 583 lignes mises à jour
* Pour le `Component` `104` : 347 lignes mises à jour
* Pour le `Component` `7159` : 84 lignes mises à jour
* Pour le `Component` `246` : 145 lignes mises à jour

## Attention :
J'aimerais avoir les ID `Component` pour la demande `Remplacer le composant bouchon «Colmate 44x24, QUALITE S» par « Colmate 44x24, QUALITE S, personnalisé Mis en bouteille en France »`

**Comment by lgiRomain** [comment]
Colmate 44x24, QUALITE S => ID 18644
Colmate 44x24, QUALITE S, personnalisé Mis en bouteille en France => ID 30416

**Comment by Portekoi** [comment]
Pour le `Component` `18644` : 143 lignes mises à jour

**Comment by Portekoi** [comment]
@lgiRomain Je te laisse vérifier et clore.

**Comment by lgiRomain** [comment]
@Portekoi tout semble s’être bien déroulé. Merci
