### ISSUE TITLE
Passer tous les Porduits en "à activer ADV" => Pastilles ROUGES

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#161]
Avec nos nouvelles CGV, merci de passer TOUS les produits de tous les CLIENTS en Pastilles ROUGES => "à activer par ADV"

**Comment by Portekoi** [comment]
C'est fait. 1598 produits impactés. Ci-joint, les produits concernés.

Table sauvegardée sous `Product20180216D`

[LGI-ProductsActivates-20180216D-1.zip](https://github.com/lgi-wines/Extranet-LGI/files/1730884/LGI-ProductsActivates-20180216D-1.zip)

**Comment by lgazeau** [comment]
MERCI
