### ISSUE TITLE
Ne plus Afficher Composants ARCHIVES > 3 ans 

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#162]
Dans COMPOSANTS => ÉTIQUETTES => STOCK

Ne plus afficher les Composants ARCHIVES depuis plus de 3 ans => cf. PJ

[LGI Composants Archivés plus de 3 ans.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1730735/LGI.Composants.Archives.plus.de.3.ans.pdf)

**Comment by lgazeau** [comment]
Dans COMPOSANTS => ÉTIQUETTES => STOCK

Ne plus afficher les Composants ARCHIVES depuis plus de 3 ans qui polluent la lecture => cf. PJ

[LGI Composants Archivés plus de 3 ans.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1730740/LGI.Composants.Archives.plus.de.3.ans.pdf)

**Comment by Portekoi** [comment]
Je trouve pas `Stock` dans cet écran. Peux tu me faire un printscreen? Merci

**Comment by lgazeau** [comment]
Pour voir l'onglet STOCK, il te faut t'abonner aux "Embouteilleurs" dans "Sécurité"


![image](https://user-images.githubusercontent.com/22617206/36319462-48bdfa64-1343-11e8-88ee-978484f667b9.png)

**Comment by Portekoi** [comment]
Je mets le lien pour accéder directement à la bonne page. 

https://lgivm.ntlm.tech/Component/Stock.aspx?ComponentID=29283

Par contre, je n'ai pas de date d'archivage mais une date de modification. Par exemple, pour `ANCIENS TEMPS E Cabernet Syrah IGP Pays d'Oc`, j'ai une date de modification à `2013-02-01 16:55:31.537`

Donc je peux voir pour masquer les composants `Etiquette` modifiés il y a plus de 3 ans et archivés.

**Comment by lgazeau** [comment]
OUI, tu peux masquer les composants Etiquette modifiés il y a plus de 3 ans et archivés.
Cela correspond à ma demande.
Tu me diras quand c'est OK

**Comment by Portekoi** [comment]
Ajout de la colonne `IsDeleted` : 
`alter table pinard.dbo.component ADD IsDeleted bit null DEFAULT 0;`

**Comment by Portekoi** [comment]
Ajout d'un `trigger` : 

```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE TRIGGER dbo.update_isdeleted
   ON  dbo.component
   For Update
AS 
BEGIN

	update component set IsDeleted = 1 where IsArchived = 1 and DATEDIFF(year, ModificationDate, getdate()) >= 3

END
GO
```

**Comment by Portekoi** [comment]
Sauvegarde de la table : 

```sql

select *
into pinard.dbo.component_20180221D
from pinard.dbo.Component
```

**Comment by Portekoi** [comment]
Mise à jour via `trigger` de la nouvelle colonne `isdeleted` : 

```sql
update pinard.dbo.Component set name = Name where DATEDIFF(year, ModificationDate, getdate())  >= 3 and IsArchived = 1
```

**Comment by Portekoi** [comment]
Résultat pour le composant `29283` : 

![image](https://user-images.githubusercontent.com/1560754/36509754-001804ea-1761-11e8-804c-e6b9dd8d0f85.png)

Je vérifie bien tout et je pense livrer demain, fin de journée.

**Comment by Portekoi** [comment]
C'est livré

**Comment by Portekoi** [comment]
J'ai archivé deux modifications. Pour la traçabilité, j'ajoute le lien vers le commit : 
https://github.com/ntlm-technologies/lgi-pinard/commit/7c7d78f5b1889ae6252a8cbc52918ef0e936c8d3#diff-2515c8d9e905c05d0ccd0ef7118b34e1

**Comment by lgazeau** [comment]
PARFAIT
