### ISSUE TITLE
Compléter Table dbo_Comptes // Créer Activité 20 "Pris sur Stock BRAND PHOENIX"

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#163]
Merci de :
• Compléter la table dbo_Comptes avec les ID 132 et 133 (cf. PJ)
• Créer dans l’Application l’ Activité 20 "Pris sur Stock BRAND PHONEIX"

Et merci de vérifier que l'utilisation de l'Activité 20 "Pris sur Stock BRND PHOENIX" ne génère aucune écriture dans la journal des ACHATS que génère Jacques.

[Table_ComptesAu27022018.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1761853/Table_ComptesAu27022018.xlsx)

**Comment by lgazeau** [comment]
Besoin de régler cette entrée pour boucler notre Fin de Mois de FÉVRIER 2018

=> Merci de :
• Compléter la table dbo_Comptes avec les ID 132 et 133 (cf. PJ)
• Créer dans l’Application l’ Activité 20 "Pris sur Stock BRAND PHONEIX"

Et merci de vérifier que l'utilisation de l'Activité 20 "Pris sur Stock BRND PHOENIX" ne génère aucune écriture dans la journal des ACHATS que génère Jacques.

[Table_ComptesAu27022018.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1770491/Table_ComptesAu27022018.xlsx)

**Comment by Portekoi** [comment]
@MamboJoel On a quelque chose de documenté pour ce type de demande?

**Comment by lgazeau** [comment]
Même demande que sur entre N° 145

Compléter Table dbo_Comptes // Créer Activité 19 "Pris sur Stock LAOZUOFANG" #145

**Comment by Portekoi** [comment]
Ca je pense pouvoir le faire. C'est la suite qui me dérange : 
`Et merci de vérifier que l'utilisation de l'Activité 20 "Pris sur Stock BRND PHOENIX" ne génère aucune écriture dans la journal des ACHATS que génère Jacques.`

**Comment by Portekoi** [comment]
C'est fait : 
![image](https://user-images.githubusercontent.com/1560754/37026484-d63a8db4-212e-11e8-8845-a5493a36ccbf.png)

**Comment by lgazeau** [comment]
OK pour la MAJ de la base

=> Merci de mettre en ligne

**Comment by meillere** [comment]
Il faut vérifier dans le code de Nicolas que l'activité 20 ne génère pas d'écriture d'achat

**Comment by Portekoi** [comment]
Et c'est là que je ne sais pas. J'ai bien complété la table `dbo.Comptes`. @meillere ou @MamboJoel ?

**Comment by Portekoi** [comment]
Ok je cherche dans la source

**Comment by Portekoi** [comment]
Je ne trouve rien. J'attends que Nico puisse jeter un oeil.

**Comment by Portekoi** [comment]
Par contre, j'ai trouvé une table `Activity `: 

![image](https://user-images.githubusercontent.com/1560754/37027264-24a123b2-2131-11e8-8e02-95674092c64b.png)

Cela semble lié...

**Comment by Portekoi** [comment]
Ok j'ai aussi complété cette table.

**Comment by Portekoi** [comment]
Les comptes ajoutés ne sont pas présents dans la table `ComptesAchat`. Je ne trouve rien dans les sources.

**Comment by Portekoi** [comment]
@lgazeau Vois tu la modification?

**Comment by lgazeau** [comment]
Activité "Pris sur Stock BRAND PHOENIX" n'apparaît toujours pas dans l'Appli

**Comment by Portekoi** [comment]
@meillere Peux tu m'aider et m'expliquer la marche à suivre? La table `Activity` est pourtant bien alimentée : 
![image](https://user-images.githubusercontent.com/1560754/37035702-a6cb5e86-214d-11e8-8b7f-cfd6f2958250.png)

**Comment by meillere** [comment]
voir avec nicolas il a du passer par des collections

**Comment by Portekoi** [comment]
```
Si tu changes quelque chose (un champ, un ligne) dans une table comme celle-là, il est possible que son contenu soit stocké en variable static dans l'application.
```

J'ai donc redémarré IIS et recyclé le pool `Pinard`

**Comment by MamboJoel** [comment]
Je pense qu'il suffit de recycler le pool.

**Comment by Portekoi** [comment]
@lgazeau Tu confirmes que c'est bon pour toi?

**Comment by lgazeau** [comment]
Cela me semble OK.
