### ISSUE TITLE
Récupérer une Bouteille dans le paramétrage "Palettisation"

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#166]
On n'a apparemment pas la main pour récupérer un type de Bouteille "créée" dans la table "Bouteille" du paramétrage de nos palettisations.

Exemple : 
Bouteille ESTELA Blanche (C
[Paramétrage Palettisation.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1825874/Parametrage.Palettisation.pdf)
omponentID 17729)
http://lgivm.waybis.com/Component/Form.aspx?ComponentID=17729

qui ne remonte pas dans la table Bouteille du paramétrage "Palettisation"
http://lgivm.waybis.com/Search/Palettisation.aspx

Voir PJ

**Comment by lgazeau** [comment]
On n'a apparemment pas la main pour récupérer un type de Bouteille "créée" dans la table "Bouteille" du paramétrage de nos palettisations.

Exemple :
Bouteille ESTELA Blanche (C
Paramétrage Palettisation.pdf
omponentID 17729)
http://lgivm.waybis.com/Component/Form.aspx?ComponentID=17729

qui ne remonte pas dans la table Bouteille du paramétrage "Palettisation"
Voir PJ
[Paramétrage Palettisation.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1825880/Parametrage.Palettisation.pdf)

**Comment by Portekoi** [comment]
Je ne vois nul part un moyen d'insérer quoi que ce soit dans la table `BottleType` depuis le portail intranet.

Je peux le faire à la main. Est-ce qu'il n'y a que `Bouteille ESTELA Blanche` à insérer?

Je joins la table actuelle au cas où.
[LGI-BotlleTypes-20180319D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1825934/LGI-BotlleTypes-20180319D-1.xlsx)

**Comment by lgazeau** [comment]
Il faut rentrer les 2 ESTELA Blanche
ComponentID=17729
ComponentID=30018
dans :
[Paramétrage Palettisation.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1825944/Parametrage.Palettisation.pdf)

**Comment by Portekoi** [comment]
Juste pour que je comprenne bien et que je ne fasse pas de bêtise : vous avez créé un composant `Bouteille` qui est aussi un type de `Bouteille` ? 

Parce que pour le `ESTELA Blanche`, je le vois en tant que composant `Bouteille` et de type `SOPHIA`

![image](https://user-images.githubusercontent.com/1560754/37610072-fee373f0-2b9e-11e8-8adc-a8a688152eef.png)

Et le type `SOPHIA` est bien dans le menu `Palettisation` : 

![image](https://user-images.githubusercontent.com/1560754/37610242-5efce5dc-2b9f-11e8-95b7-873746e05454.png)

**Comment by lgazeau** [comment]
J'ai compris.
Eric a sélectionné le Type SOPHIA au niveau du composant car il n'a pas la main pour créer un Type au niveau du composant. 
Il faut créer (ou lui permettre de créer) le Type ESTELA pour qu'il puisse le retrouver dans le menu "Palettisation"

**Comment by Portekoi** [comment]
C'est fait. 
![image](https://user-images.githubusercontent.com/1560754/37668756-85c03af4-2c65-11e8-92e9-f0c889064014.png)

**Comment by lgazeau** [comment]
Parfait.

Merci
