### ISSUE TITLE
Débit habillage en trop - 2 fois pour une commande

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#167]
Sur les composants ID 29378 et 29234, la commande 38387 de 1200 bouteilles à été débitée 2 fois dans l'entrepot Cebazan GVSC, un fois par l'utilisateur "nicolas" la nuit dernière et une fois par Stéphanie Josneau aujourd'hui lors de la facturation.

Que s'est-il passé ?
Les stocks habillages sont faux et négatifs

**Comment by Portekoi** [comment]
C'est très étrange. De mémoire, une routine passe la nuit pour débiter les composants pour les mises produits. Etrange que cela se soit aussi produit à la facturation. Est-ce le seul cas? Y a t il déjà eu cela avant?

**Comment by Portekoi** [comment]
@lgiRomain : pense à assigner Nico ou moi via le menu de droite : 

![image](https://user-images.githubusercontent.com/1560754/38167486-c580739c-3535-11e8-8e26-1d0b8f9b5690.png)

**Comment by lgiRomain** [comment]
Pas de souvenir de cas identiques...
On a fait la correction à la main, mais il faut garder un oeil sur ce genre de problème si cela se reproduit
