### ISSUE TITLE
URGENT : création activité PRIS SUR STOCK PLUMERIDGE 

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#168]
Bonjour,
URGENT
Pour création activité PRIS SUR STOCK PLUMERIDGE sur la même stricte base que l’activité Pris sur stock Brandphoenix créée récemment.

	Code comptable pour l’export vers SAGE des ACHATS : 60713700
	Code comptable pour l’export vers SAGE des VENTES : 70793400

merci
Stéphanie

**Comment by josneaulgi** [comment]
RELANCE 1

**Comment by Portekoi** [comment]
Il faut assigner quelqu'un sinon, on est pas alerté directement : 
![image](https://user-images.githubusercontent.com/1560754/38297873-090a54f8-37f6-11e8-9bca-70fa4c357862.png)

Je n'ai pas les éléments pour traiter ce type de demande. Je ne sais pas quelles tables il faut modifier. @MamboJoel ou @meillere, pouvez vous me donner les éléments? Merci

**Comment by josneaulgi** [comment]
http://lgivm.waybis.com/Kart/Form.aspx?KartID=38588
vous voyez activité : Pris sur Stock Singapore à côté de Achat Embouteilleur
on aimerait mettre à la place Pris sur Stock Plume Ridge. (laisser Singapore à Singapore).
merci

**Comment by josneaulgi** [comment]
oui, c'est ici qu'il faut rajouter Pris sur stock Plume Ridge. 
en attendant que ce soit créé, on a mis volontairement Pris sur stock Singapore.

**Comment by MamboJoel** [comment]
Ok je pense avoir trouvé. En revanche @josneaulgi je ne vois aucun dispositif mis en place pour le compte charges (6), seulement pour les produits (7).

@Portekoi j'ai documenté [ce wiki](https://github.com/ntlm-technologies/lgi-pinard/wiki/_new).

En tout cas la gestion des activités de cette manière, au niveau des commandes, est une erreur manifeste de design. Le premier symptôme est que sur la page de la commande d'un client A on laisse l'utilisateur choisir une activité d'un client B.

**Comment by josneaulgi** [comment]
	Code comptable pour l’export vers SAGE des ACHATS - CHARGES (6) : 60713700
	Code comptable pour l’export vers SAGE des VENTES - PRODUITS (7) : 70793400

regardes comment c'est fait avec les autres Prises sur stock

**Comment by meillere** [comment]
Le champ compteproduit de la table activité ne sert à rien, cette table n'est que le support de la liste déroulante.
C'est la table compte qu'il faut renseigner en fonction de l'activité.

![image](https://user-images.githubusercontent.com/22621226/38320420-6dbffa0c-382c-11e8-8c41-384f89746ecc.png)

**Comment by meillere** [comment]
J'ai renseigné la table comptes
il faut vérifier la colonne vatlaw j'ai mis 3 =export cela doit être bon s'il est hors europe.
![image](https://user-images.githubusercontent.com/22621226/38320668-1f7c2b80-382d-11e8-8116-4e4be81516ed.png)

**Comment by josneaulgi** [comment]
c'est ok pour Plume Ridge car c'est bien du grand export.
pour info, le 1 c'est pour livraison France et le 2 c'est pour livraison Europe.
tout est dans l'ordre.
merci

**Comment by MamboJoel** [comment]
Merci Jacques.

**Comment by Portekoi** [comment]
Super, merci !
