### ISSUE TITLE
Compléter LETTRAGE (mode COURTAGE only) 

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#172]
Aurions besoin de Compléter LETTRAGE ("mode COURTAGE" only) 

"Recherches lettrages"

Mode Lecture écran et export XPL

cf. Exemple en PJ pour le ClientID 102 SLIGRO

[Compléter LETTRAGE (mode COURTAGE only) ClientID 102 SLIGRO.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1987329/Completer.LETTRAGE.mode.COURTAGE.only.ClientID.102.SLIGRO.pdf)

**Comment by Portekoi** [comment]
Je suis désolé mais j'ai rien compris. Cela apparait sur quel écran? A partir d'une commande/d'un module?

**Comment by lgazeau** [comment]
[Compléter LETTRAGE (mode COURTAGE only) ClientID 102 SLIGRO.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1987697/Completer.LETTRAGE.mode.COURTAGE.only.ClientID.102.SLIGRO.pdf)
Client SLIGRO Client ID 102
Bas de la page "Lettrage"
Pavé "Recherche lettrages" avec possibilité de faire une sortie .XLS
=> voir PJ

**Comment by Portekoi** [comment]
OK j'ai compris. Je regarde.

**Comment by Portekoi** [comment]
Je termine l'exportation Excel et je te dis. Mais je vais livrer après 18h pour ne pas vous gêner.

**Comment by lgazeau** [comment]
OK

**Comment by lgazeau** [comment]
Parfait
Tu peux livrer quand tu veux

**Comment by Portekoi** [comment]
Ok. J'attends 18h. Je veux pas qu'il y ait de problème et que cela vous pénalise.

**Comment by Portekoi** [comment]
C'est livré.

**Comment by Portekoi** [comment]
Je clos.

**Comment by lgazeau** [comment]
OK
