### ISSUE TITLE
Le bouton "Extranet" sur le LGI2 Appro ne fonctionne

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#177]
Sur le nouveau système d'appro LGI 2, le bouton "Extranet", qui sert de passerelle pour aller sur le composant en question sur WB, et qui se trouve sur chaque composant sur chaque commande (non validée), ne fonctionne plus

**Comment by Portekoi** [comment]
je viens de tester et je n'ai aucun problème. Que se passe t il? Y a t il un message d'erreur par exemple?

**Comment by Portekoi** [comment]
J'ai testé sur cette commande : http://ui.lgi.ntlm.technology/order/104509

**Comment by lgiRomain** [comment]
[NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.]    Waybis.Pinard.Web.Navigation.ComponentNavigation.Init() in D:\_Stockage\_Boulot\NTLM\Repositories\LGI\lgi-pinard\Web\App_Code\Navigation\Component.vb:51    Waybis.Pinard.Web.Navigation.ComponentNavigation..ctor(Component Component) in D:\_Stockage\_Boulot\NTLM\Repositories\LGI\lgi-pinard\Web\App_Code\Navigation\Component.vb:31    Waybis.Pinard.Web.EntityBasePage.GetEntityNavigation(IEntity Entity) in D:\_Stockage\_Boulot\NTLM\Repositories\LGI\lgi-pinard\Web\App_Code\EntityBasePage.vb:100    Waybis.WebControls.EntityBasePage.OnInit(EventArgs e) in D:\_Stockage\_Boulot\NTLM\Repositories\Waybis\waybis-common\Controls\Pages\EntityBasePage.vb:111    System.Web.UI.Control.InitRecursive(Control namingContainer) +165    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +410
--

**Comment by lgiRomain** [comment]
Effectivement, il n'y a que moi chez qui cela ne fonctionne. Mais même en me reconnectant, cela ne fonctionne pas

**Comment by Portekoi** [comment]
Tu peux me donner le lien de la commande?

**Comment by lgiRomain** [comment]
http://ui.lgi.ntlm.technology/order/103277

**Comment by lgiRomain** [comment]
C'est bon ça fonctionne maintenant. Merci

**Comment by lgiRomain** [comment]
Idem, le bouton ne fonctionne plus, même si je me déconnecte et reconnecte

**Comment by Portekoi** [comment]
Déconnecte et reconnecte sur quel site? C'est bien sur l'ancienne url qui n'est pas en https?  
http://lgivm.waybis.com/ ?

**Comment by lgiRomain** [comment]
Non, sur le système d'appro http://ui.lgi.ntlm.technology

**Comment by Portekoi** [comment]
Ok. C'est compliqué à expliquer par écrit. Il faut te reconnecter et t'identifier à l'ancien lien qui est : 
http://lgivm.waybis.com/

Une fois que c'est fait, cela devrait refonctionner du côté des appros.

**Comment by lgiRomain** [comment]
Ok ca fonctionne
