### ISSUE TITLE
Recherche COMMANDES => Segmentation ANNEE

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#178]
Dans l'onglet COMMANDES
et dans 
CLIENT\COMMANDES
on peut chercher par le menu déroulant sur 
* 6 derniers mois
* EN cours de saisie
* Toutes 
* attente de validation
...
on aimerait maintenant rechercher sur une "année calendaire" donnée, et non pas "12 Mois glissants" 
=> il nous faudrait donc une segmentation "Année" : N, N-1
en travaillant toujours sur Depature Date/Invoice Date

Est-ce faisant facilement ?

**Comment by Portekoi** [comment]
Je regarde et je te dis ça dès que possible.

**Comment by Portekoi** [comment]
Ca devrait être bon mais c'est très long et gourmand en ressources. A utiliser avec Parcimonie.

**Comment by lgazeau** [comment]
Super
MERCI
