### ISSUE TITLE
LIASSE DE COMMANDE sans FICHE DEVIS

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#181]
Lorsqu'on clique depuis un Kart (cf. KartID 40512 en PJ) sur l’onglet « LIASSE DE COMMANDE », pour imprimer les commandes, s'insère entre chaque ordre de mise (chaque produit), une FICHE DEVIS du produit concerné. 

Il me semble qu'on avait initialement créé  2 LIASSE DE COMMANDE 
* LIASSE DE COMMANDE avec FICHE DEVIS
* LIASSE DE COMMANDE sans FICHE DEVIS
=> Pouvez-vous récréé un nouvel onglet "LIASSE sans FICHE DEVIS" à côte de l'onglet "LIASSE DE COMMANDE" existant
Par ailleurs, l'onglet "DETAIL" peut être supprimé.
D'avance merci.
[LIASSE DE COMMANDE sans FICHE DEVIS (KartID 40512).pdf](https://github.com/lgi-wines/Extranet-LGI/files/2052717/LIASSE.DE.COMMANDE.sans.FICHE.DEVIS.KartID.40512.pdf)

**Comment by Portekoi** [comment]
OK je vais regarder.

**Comment by lgazeau** [comment]
ERRATUM

EN fait, c’est OK => ne pas tenir pas compte de cette Issue#181
C'est bien ce que je pensais, Sébastien s’était juste trompé de cession.
