### ISSUE TITLE
Export PLANNING : raffinage 

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#184]
Dans l'Export PLANNING : compléter BF par le N° Mise

AU lieu de n'avoir que "BF" dans le champ "Cde", compléter par "BF N° Mise"

=> Paramétrage => Embouteilleurs => CELLIERS JEAN D'ALIBERT => Planning => A planifier :
Cf. PJ "BF" => "BF 202052" ; ou "BF" => "BF 202785"

[Compléter BF par N° Mise dans Export PLANNING.pdf](https://github.com/lgi-wines/Extranet-LGI/files/2076586/Completer.BF.par.N.Mise.dans.Export.PLANNING.pdf)

**Comment by Portekoi** [comment]
C'est donc le même chiffre qui est en début de ligne? Ok je vais regarder.

**Comment by Portekoi** [comment]
Dis moi si cela te convient.  Je n'ai pas pu accéder à `CELLIERS JEAN D'ALIBERT` pour vérifier.

![image](https://user-images.githubusercontent.com/1560754/41318547-00e76b2e-6e99-11e8-8e60-5b5b9787310a.png)

**Comment by lgazeau** [comment]
OK
