### ISSUE TITLE
Liste composant cartons et capsules créés en 2017

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#185]
Messieurs, j'ai besoin de votre aide:
Pouvez vous me sortir une liste excel avec tous les composants "Caspule" et "Caisse" créés sur l'année 2017, avec à côté le fournisseur par défaut et les quantités utilisées svp?

Deadline: jeudi 14 Juin si possible svp

Merci d'avance

**Comment by Portekoi** [comment]
Pour les quantités utilisées, il faut que je creuse au niveau de la base. Je regarde dès que possible.

**Comment by Portekoi** [comment]
Capsule : 
[LGI-Capsule-QtyUsed-20180612D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/2095800/LGI-Capsule-QtyUsed-20180612D-1.xlsx)

**Comment by Portekoi** [comment]
Capsule
[LGI-Capsule-QtyUsed-20180612D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/2095810/LGI-Capsule-QtyUsed-20180612D-1.xlsx)

**Comment by Portekoi** [comment]
Caisse
[LGI-Caisse-QtyUsed-20180612D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/2095816/LGI-Caisse-QtyUsed-20180612D-1.xlsx)

Pour les deux : 

```sql
select capsule.id as ComponentID, capsule.Name, capsule.DefaultSupplierID, supplier.name, coalesce(sum(UnitQuantity), 0) as nb from component as capsule
left outer join orderitem as oi on capsule.id = oi.articleID
left outer join Supplier on supplier.id = capsule.DefaultSupplierID
where year(capsule.Creationdate) = 2017 and capsule.ComponentType = 9
group by capsule.id, capsule.Name, capsule.DefaultSupplierID, supplier.name

```

**Comment by Portekoi** [comment]
Dis moi si cela te va. Merci.

**Comment by lgiRomain** [comment]
@Portekoi tu me confirmes que ces composants ont tous été créés en 2017 ?

**Comment by Portekoi** [comment]
Oui tout à fait. Année de création : 2017

**Comment by lgiRomain** [comment]
C'est ok merci

**Comment by lgiRomain** [comment]
Je ne sais pas comment ca se fait, mais les quantités ne sont pas tout cohérentes. Elles ne correspondent pas du tout à la réalité

**Comment by Portekoi** [comment]
Pour les quantités utilisées, j'ai pris toutes les commandes. Qu'entends tu par `Quantités utilisées`?

**Comment by lgiRomain** [comment]
Ce qui m’intéresse, c'est de savoir pour chaque composant capsule et carton, combien en a-t-on utilisé pour les commandes clients. 
En résumé, faire le total utilisé pour toute les commandes clients, par composant

**Comment by Portekoi** [comment]
Ok je pense avoir compris mon erreur. Je regarde.

**Comment by Portekoi** [comment]
@lgiRomain Si tu peux, regarde le fichier ci-joint et dis moi si cela te semble bon niveau quantité. Merci.


[LGI-Component-Qty-Box-9-20180614D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/2102444/LGI-Component-Qty-Box-9-20180614D-1.xlsx)

**Comment by lgiRomain** [comment]
Oui c'est bon cette fois ci. Il me faut la même chose pour les capsule stp

**Comment by Portekoi** [comment]
[LGI-Component-Qty-Caps-6-20180614D-1.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/2102569/LGI-Component-Qty-Caps-6-20180614D-1.xlsx)

**Comment by Portekoi** [comment]
Dis moi si c'est bon pour toi. Et désolé pour le premier fichier. Je suis allé un peu (trop) vite.

```
select  c.id as ComponentID, c.name as ComponentID, s.name as SupplierName, sum(kp.TotalNumberOfBottles) as Qty from Kart as k
inner join KartProduct as kp on k.ID = kp.Kartid
inner join Product as p on kp.productID = p.id
inner join ProductComponent as pc on p.id = pc.productID
inner join Component as c on pc.ComponentID = c.id 
inner join Supplier as s on  s.id = c.DefaultSupplierID
where year(c.Creationdate) = 2017 and c.ComponentType = 6
group by  c.id, c.name, c.DefaultSupplierID, s.name
```

**Comment by lgiRomain** [comment]
C'est impec merci
