### ISSUE TITLE
Suppr Accise Number from Delivery Note

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#194]
Il faut supprimer le Accise Number de la Delivery Note cf. PJ
et de tous les autres supports d'ailleurs car nous n'avons plus de N° d'Accise

Merci de faire le nécessaire
[LGI Delivery Note Accise Number à supprimer.pdf](https://github.com/lgi-wines/Extranet-LGI/files/2192450/LGI.Delivery.Note.Accise.Number.a.supprimer.pdf)

**Comment by Portekoi** [comment]
C'est bon pour ce document. Dis moi si ce numéro est autre part sur l'intranet.

**Comment by lgazeau** [comment]
Ca à  l'air OK
