### ISSUE TITLE
ClientRename : fusionner les clients "British Columbia Liquor Distribution Branch" (Client ID : 213) et "British Columbia Liquor Distribution Branch" (Client ID : 1335) sous "British Columbia Liquor Distribution Branch" (Client ID : 1335)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#198]
Jacques,

Dans le REPORTING, merci de fusionner les clients British Columbia Liquor Distribution Branch (Client ID : 213) et British Columbia Liquor Distribution Branch (Client ID : 1335) sous British Columbia Liquor Distribution Branch (Client ID : 1335)

Vous utilisez la table « ClientRename » => il faudrait que j’ai la main sur cette table.

Merci de me dire quand c’est OK.

**Comment by meillere** [comment]
J'ai renseigné la table client rename.
Je laisse Nicolas ou Damien modifier l'administration pour permettre à Laurent de renseigner cette table.
