### ISSUE TITLE
Bon d'achat en trop - Commande client 41324

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#204]
### Description
Un bon d'achat "Celliers Jean d'Alibert" apparait sur la commande 41324

### Scénario pour reproduire l'anomalie
On saisit la commande 41324 sur la fiche produit 32924 

### Résultat attendu
Seulement 2 bons d'achat devraient apparaitre sur la commande 41324: "UCC" et "CJA - Prestation de Service"

### Anomalie constatée
Un troisième bon d'achat apparait "Cellier Jean d'Alibert"

**Comment by Portekoi** [comment]
@lgiRomain L'anomalie semble avoir disparu : 

![image](https://user-images.githubusercontent.com/1560754/43510636-8b5a4bf6-9576-11e8-88f2-23749bcd9b24.png)

Tu me confirmes?

**Comment by lgiRomain** [comment]
@Portekoi je te confirmes.

Merci
