### ISSUE TITLE
ClientRename : fusionner les clients "NOTIFY: REAL COMERCIAL LTDA" (Client ID : 857) et "NOTIFY / BUYER: REAL COMERCIAL EIRELI" (Client ID : 1242) sous "NOTIFY: REAL COMERCIAL LTDA" (Client ID : 857) 

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#208]
Idem #198 

Dans le REPORTING, merci de fusionner les clients "NOTIFY: REAL COMERCIAL LTDA" (Client ID : 857) et "NOTIFY / BUYER: REAL COMERCIAL EIRELI" (Client ID : 1242) sous "NOTIFY: REAL COMERCIAL LTDA" (Client ID : 857) 

Vous utilisez la table « ClientRename » => il faudrait que j’ai la main sur cette table.
Merci de me dire quand c’est OK.

**Comment by Portekoi** [comment]
C'est fait.

**Comment by lgazeau** [comment]
C'est OK
Parfait
MERCI
