### ISSUE TITLE
N° "Compte compta fourn" obligatoire

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#209]
Interdire l'enregistrement d'un FOURNISSEUR (Paramétrage\Fournisseurs)
si le champ "Compte compta fourn" n'est pas renseigné

Cela fonctionne pour les CLIENTS
si le champ "Compte compta client" n'est pas renseigné => on ne peut pas enregistrer le CLIENT

**Comment by Portekoi** [comment]
Ok pour moi. Je livre.

![image](https://user-images.githubusercontent.com/1560754/45352116-0bb7b980-b5b8-11e8-89df-3d6bfea1d44d.png)

**Comment by Portekoi** [comment]
Livré : 
![image](https://user-images.githubusercontent.com/1560754/45352567-1292fc00-b5b9-11e8-8724-f0a517eb5c27.png)
