### ISSUE TITLE
Mention FACTURE

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#21]
Faire en sorte que "Editer facture" affiche pour tous les statuts jusqu'à "Facturée" la mention PROFORMA, c'est à dire pour 👍 
* En cours de saisie
* Validée
* Transmis à la cave
* Expédiée

A partir du statut "Facturé" PROFORMA devient INVOICE + Inv. N°

**Comment by josneaulgi** [comment]
RELANCE

**Comment by josneaulgi** [comment]
Est ce que tu peux traiter ?

**Comment by MamboJoel** [comment]
Ok pour ça.
On a procédé à l'inverse : on affiche PROFORMA systématiquement sauf pour les statuts "Facturée" et "Payée". Et traitement des langues français/anglais.
