### ISSUE TITLE
Bug Enregistrement COMPOSANT ou FICHE PRODUIT

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#212]
Depuis les MAJ de ce jour, nous levons systématiquement une erreur à l'enregistrement d'un COMPOSANT ou d'une FICHE PRODUIT
=> voir PJ

Par contre, en revenant sur le COMPOSANT ou la FICHE PRODUIT la MAJ a bien été faite !

![r](https://user-images.githubusercontent.com/22617206/45370559-ce1f5480-b5e8-11e8-98c8-d5063d7c7904.png)

**Comment by Portekoi** [comment]
Ce n'est pas lié. Nous rencontrons des problèmes avec l'un de nos serveurs qui assure la synchronisation v1 - v2 et il ne répondait plus.
