### ISSUE TITLE
URGENT - Impossibilité tout Enregistrement 

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#217]
Impossibilité d'Enregistrer toutes modifs dans l'Appli v1

Une MAJ n'a pas du passer

HELP

**Comment by Portekoi** [comment]
Je regarde.

**Comment by Portekoi** [comment]
Je publie sur test d'abord puis sur prod si tout est ok

**Comment by Portekoi** [comment]
Je vais livrer en production dans 5 minutes.

**Comment by Portekoi** [comment]
Je relivre. Mauvais patch...

**Comment by Portekoi** [comment]
OK ca devrait être bon @lgazeau 

On a encore un souci avec l'un de nos serveurs qui assure la syncrho entre v1 et v2. Votre saisie s'enregistre bien mais vous aviez ensuite un message d'erreur. 

Ca devrait être bon maintenant.

**Comment by lgazeau** [comment]
Ca a l'air OK
@ suivre
Merci
