### ISSUE TITLE
REPORTING : Client Rename (Client ID 1185 et 1340 deviennent 987)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#219]
Jacques,

Dans le Reporting, merci de fusionner les clients XIAMEN SEASHINE INTERNATIONAL TRADE CO., LTD. po BEIJING DE LI BAO (Client ID : 1185) et BONABI'ANG INTERNATIONAL TRADE (BEIJING) CO., LTD. (Client ID : 1340) sous BEIJING DE LI BAO COMMERCE AND TRADE CO. LTD (Client ID : 987)

Vous utilisez la table « ClientRename ».

Merci de me dire quand c’est OK.

**Comment by Portekoi** [comment]
@lgazeau 
Ca devrait être bon.

**Comment by lgazeau** [comment]
Non ce n'est pas encore bon => voir PJ
Tout doit être sur le ClientID 987, pour 2017 et 2018 
[LGI_Report_DE LI BAO.pdf](https://github.com/lgi-wines/Extranet-LGI/files/2434649/LGI_Report_DE.LI.BAO.pdf)

**Comment by Portekoi** [comment]
Je viens de refaire la manipulation. Tu diras si c'est bon.

**Comment by lgazeau** [comment]
Pour moi cela n'est toujours pas bon
=> voir Stat 2017 2018 en PJ

[LGI_Report_DE LI BAO.pdf](https://github.com/lgi-wines/Extranet-LGI/files/2437058/LGI_Report_DE.LI.BAO.pdf)

**Comment by Portekoi** [comment]
Tu peux me dire dans quel menu tu vas pour avoir ce tableau?

**Comment by lgazeau** [comment]
LGI REPORTING
Niveau Pays Client
Sélectionner Pays : CHINE
Charger les données
http://lgirep.waybis.com/Commandes/TCPaysClient.aspx

**Comment by Portekoi** [comment]
@meillere Si tu peux me donner des infos parce que je pense avoir fait comme les autres fois sauf que cela ne fonctionne pas.

**Comment by meillere** [comment]
J'ai réglé le problème.

cela venait du fait que dans la table clientrename il y avait deux entrées contradictoires.
987 devenait 1185 ancienne et 1185 devenait 987 nouvelle entrée
Quand Laurent demande un client rename il faut vérifier qu'il n'y a pas une autre entrée concernant ce client, c'est arrivé plusieurs fois.

**Comment by Portekoi** [comment]
Ok top. Merci :)
