### ISSUE TITLE
TDB direct Excel 2019

### ISSUE THREAD

**Issue by meillere** [lgi-wines/Extranet-LGI#220]
ci joint le fichier à tester

[TDB_Direct_2019.zip](https://github.com/lgi-wines/Extranet-LGI/files/2442189/TDB_Direct_2019.zip)

**Comment by lgazeau** [comment]
Petit Twist sur la cellule B8 de "Bas TDB 2018"
Peux-tu me la corriger ?
D'avance merci.

**Comment by meillere** [comment]
[TDB_Direct_2019.zip](https://github.com/lgi-wines/Extranet-LGI/files/2460870/TDB_Direct_2019.zip)
Correction
