### ISSUE TITLE
ProductID sur Fiches Palette, en bas à droite

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#27]
Pour CEBAZAN : besoin de faire apparaître le ProductID sur Fiches Palette, en bas à droite

Exemple 
ProductID = 25512 
pour le produit
PIERRE ET PAPA IGP Pays d’Hérault VINOVUM Rouge 2015 75 cl .

Cela faciliterait pour les inventaires.

**Comment by MamboJoel** [comment]
Ok !
