### ISSUE TITLE
Liens des Alertes LGI Auto pointent sur l’ancienne extranet

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#28]
Les liens des "Alertes LGI Auto" pointent toujours sur l’ancienne adresse : extranet.lgi-wines.com 
=> A modifier pour pouvoir ouvrir les commandes depuis l'alerte, à parti du lien.

Exemple :
Laurent GAZEAU,

La commande 30899 transmise a la cave

Type : Negoce
Embouteilleur : UCC

Client : BEIJING JINGDONG CENTURY TRADING CO.LTD
Mise a disposition : 12/12/2016
Nombre de caisses : 1860
Nombre de cols : 11160
Voir la commande

**Comment by MamboJoel** [comment]
C'est corrigé.
