### ISSUE TITLE
Alertes LGI Auto <lgi-orders@lgi-wines.com> arrivent en double

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#29]
Alertes LGI Auto <lgi-orders@lgi-wines.com> arrivent en double

sur les adresses @lgi-wines.com

**Comment by MamboJoel** [comment]
Je ne vois ce que tu veux dire par "Alertes LGI Auto". J'ai fait une recherche sur l'ensemble du code LGI et je n'ai jamais trouvé cette occurrence. 
Est-ce que tu parles de [l'onglet Mailing de la fiche produit](http://lgivm.waybis.com/Product/Mailing.aspx?ProductID=20000) ?

**Comment by MamboJoel** [comment]
Ok, en lisant #23 j'ai compris de quoi tu parles : des notifications à l'embouteilleur quand on transmet une commande à la cave.

**Comment by MamboJoel** [comment]
Comme précisé dans #23 j'ai lancé une notification pour la commande 30915.

- Je suis surpris car il y a une vingtaine de destinataires pour ces mails. C'est beaucoup non ?
- Etant l'un de ces destinataires j'ai reçu le mail une seule fois. Je ne reproduis donc pas l'anomalie.

Pour m'aider il me faudrait plus d'informations. Comme les dates d'envoi de chacun des mails en double.

**Comment by Portekoi** [comment]
L'anomalie a-t-elle persistée? @lgazeau

**Comment by josneaulgi** [comment]
je ne peux pas non plus clore
