### ISSUE TITLE
AFFICHE PALETTE PAS CORRECTE

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#34]
ce n'est toujours pas bon.

Dans Expéditeur, il apparaît toujours
UCC CEBAZAN
RN 112
34 360 CEBAZAN
FRANCE

à la place, il faut mettre : LGI SAS
http://lgivm.waybis.com/KartProduct/PalletFile.aspx?KartProductID=78392

**Comment by MamboJoel** [comment]
Corrigé. 
Dans un cas comme celui-ci, merci de ne pas ouvrir une autre issue, mais de rouvrir l'issue initiale.
Une issue = Une problématique.

**Comment by josneaulgi** [comment]
je ne sais pas comment on fait, c'est pour ça que j'ai créé une autre issue

**Comment by MamboJoel** [comment]
Il suffit de retourner sur l'issue qui a été fermée et d'écrire un message, comme tu viens de le faire et moi avec celui-ci.
