### ISSUE TITLE
les mises ne se produisent pas automatiquement

### ISSUE THREAD

**Issue by LEBRUNPhilippe** [lgi-wines/Extranet-LGI#41]
Bonjour Nicolas,

Désolé de ne pas réouvrir l'issue concernant ce problème mais je ne la retrouve pas.

Je ne m'en suis rendu compte qu'hier, les mises ne se sont pas produites automatiquement depuis le 02 Janvier.

Peux tu regarder ça stp?

Merci. Philippe

**Comment by MamboJoel** [comment]
Bonjour Philippe,

Je suis en réunion toute la journée. Je regarde dès que j'ai une fenêtre. En l'état :

- Je constate comme toi que les mises ne sont pas produites.
- La routine pourtant s'exécute. (Dernière exécution cette nuit).
- Je viens de la lancer manuellement.

Nicolas

**Comment by LEBRUNPhilippe** [comment]
Nicolas,
La routine manuelle a fonctionné, je te dirai demain matin si la routine automatique fonctionne maintenant.
Merci.

Philippe

**Comment by MamboJoel** [comment]
Très bien. On suit.

**Comment by LEBRUNPhilippe** [comment]
Nicolas,

Les mises d'hier (mardi 10) ne se sont pas produites à la routine de cette nuit.

Philippe

**Comment by MamboJoel** [comment]
Lancée à la main pour te dépanner.
J'analyse le problème.

**Comment by Portekoi** [comment]
@MamboJoel J'ai trouvé, je pense, le script de routine (`DailyRoutine` ?) mais je ne trouve rien sur le serveur qui exécute cette tâche. Tu peux m'en dire plus que je piste le problème?

**Comment by MamboJoel** [comment]
C'est une tâche planifiée. Ce script exécute deux types de traitements, et l'on passe un argument à la commande pour déterminer lequel doit être effectué. Pour la routine nocturne de production des mises en bouteille c'est "NightRoutine"

**Comment by LEBRUNPhilippe** [comment]
Nicolas,
Je n'avais pas fait attention, les mises en bouteille ne se produisent plus automatiquement depuis le 30 octobre. Peux tu rétablir cette production automatique le soir même des mises, s'il te plait?
Merci.

Philippe

**Comment by MamboJoel** [comment]
OK. Je regarde.

**Comment by Portekoi** [comment]
NightRoutine était désactivée. Je viens de la réactiver.

**Comment by MamboJoel** [comment]
On regarde demain.

**Comment by LEBRUNPhilippe** [comment]
Bonjour.
La routine a fonctionné. A ce jour, les mises se produisent à J+1, est-il possible de reprogrammer pour que les mises se produisent le soir même?
Merci. Philippe

**Comment by Portekoi** [comment]
Le batch est bien passé et n'a pas terminé en erreur.

**Comment by Portekoi** [comment]
@LEBRUNPhilippe Si je comprends bien, ce sont toutes les mises jusq'au 8 novembre inclu qui on été produites?

**Comment by LEBRUNPhilippe** [comment]
Oui, c'est ça

**Comment by Portekoi** [comment]
C'est livré. Merci de me tenir au courant, si tout est bon.

**Comment by Portekoi** [comment]
Le batch est bien passé.

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
Je viens de m'apercevoir que les mises du Planning UCC ne se produisent plus en automatique depuis vendredi 20/07.
Peux-tu regarder ce problème, stp?
Merci.
Philippe

**Comment by Portekoi** [comment]
Je viens de la relancer à la main. Bizarrement, le serveur ne semble plus exécuter les tâches planifiées depuis le 19 juillet.

Exemple : 
![image](https://user-images.githubusercontent.com/1560754/43289252-b0c9d6e0-912a-11e8-8cfb-8ef2f15d93db.png)

A voir si cela continue. Je regarderai demain.

**Comment by Portekoi** [comment]
Ca me semble bon. @LEBRUNPhilippe Tu peux confirmer et fermer cette issue si c'est bon? Merci

**Comment by LEBRUNPhilippe** [comment]
Bonjour, oui tout semble OK. Je ferme l'issue. Merci

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
Le problème est revenu, les mises ne se produisent plus automatiquement.
Merci d'avance.
Philippe

**Comment by Portekoi** [comment]
Je ne sais pas pourquoi cette case n'est plus cochée... Je viens de la remettre : 
![image](https://user-images.githubusercontent.com/1560754/45143402-7f725480-b1bb-11e8-822a-44fdcd8f3955.png)

@LEBRUNPhilippe Je peux lancer la tâche maintenant ou tu préfère attendre ce soir?

**Comment by Portekoi** [comment]
@LEBRUNPhilippe La tâche semble s'être exécutée : 

![image](https://user-images.githubusercontent.com/1560754/45211547-e151bd80-b292-11e8-86ff-192586d3f0de.png)

**Comment by LEBRUNPhilippe** [comment]
C'est tout bon, je ferme. Merci
