### ISSUE TITLE
Bon de fabrication - Champ boîte

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#42]
Remonté par Romain : 

> Le champ « Boite » renseigné dans la fiche produit n’apparait plus de la [bon de fabrication](http://lgivm.waybis.com/Manufacturing/FabricationBill.aspx?ManufacturingID=180501), donc les opérateurs sur ligne ne savent pas quelle boite prendre.

**Comment by MamboJoel** [comment]
[Le produit en question](http://lgivm.waybis.com/Product/ComponentList.aspx?ProductID=26450).

**Comment by RomainLGI** [comment]
Dans l'attente de la résolution

**Comment by MamboJoel** [comment]
C'est corrigé.
