### ISSUE TITLE
Suppression millésime 

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#45]

**Comment by RomainLGI** [comment]
Sur le composant "Vin en bouteille" n°24671, quand je sélectionne l'option qui est vide (pas de millésime) dans le champ "Millésime", il y a un message d'erreur.
http://lgivm.waybis.com/Component/Form.aspx?ComponentID=24671

**Comment by MamboJoel** [comment]
Je l'ai corrigé.
