### ISSUE TITLE
Suppression budget Enotria 

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#50]
bonjour,
merci de supprimer les budgets sur notre client ENOTRIA
1- sur toutes les commandes FACTUREES à partir du 01.01.17 
2- sur toutes les commandes en cours 
3- sur les fiches produits ACTIFS 
Appelez moi si vous avez des questions.
merci

**Comment by josneaulgi** [comment]
RELANCE - MEGA URGENT

**Comment by MamboJoel** [comment]
C'est une manipulation périlleuse et qui demande à ce qu'on l'effectue avec soin. Comme il s'agit d'une routine exécutée en batch il y a des risques de perdre des données, d'écraser des données non voulues.

**Comment by MamboJoel** [comment]
En ce qui concerne les commandes encours, cela concerne 32 produits commandés :

31231	6
31232	6
31233	6
31254	6
31326	6
31327	6
31328	6
31329	6
31426	6
31427	6
31490	6
31491	6
31508	6
31510	6
31697	6
31698	6
31699	6
31700	6
31781	6
31830	6
31831	6
31871	6
31881	6
31882	6
32020	6
32021	6
32073	4
32137	4
32153	6
32262	4
32263	4
32266	4

La première colonne est l'ID de la commande. La seconde est son statut qui prend pour valeur 6 pour "facturé" et 4 pour en cours.

Est-ce que ça correspond ?

**Comment by MamboJoel** [comment]
Et 56 produits :

21960
22178
23426
23453
24013
24600
24840
25387
25511
25514
25551
25552
25557
25598
25755
25759
25820
25823
25844
25846
25872
26145
26147
26148
26160
26173
26279
26324
26427
26432
26444
26602
26603
26604
26817
26823
26853
26855
26856
26857
26860
26861
27150
27170
27171
27172
27173
27174
27175
27176
27178
27179
27221
27222
27242
27409

**Comment by MamboJoel** [comment]
On a effectué les traitements. Si ça vous va vous pouvez clore cette issue.
