### ISSUE TITLE
PROBLEME IMPORTANT ET URGENT: changement automatique des dates de livraison dans le nouveau système d'appro

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#53]
Quand nous modifions des dates de livraisons de commandes sur le nouveau systèmes d'appro, les dates se changent seules sans qu'on s'en aperçoive. Ce qui engendre de graves problèmes sur la plannification des mises en bouteille.

EX: commande 93301: nous changeons la date de livraison au 19/04 + clic sur "Modifier", puis quand nous revenons sur cette commande plus tard, la date s'est automatiquement repassée à 18/04.

Sur certaines commandes, nous avions sélectionné la date du lundi, et automatiquement elle se changée avec 1 jour avant, c'est à dire le dimanche.

**Comment by Portekoi** [comment]
Je reproduis en local. L'heure reçue au niveau du WS est le 18/04 si je mets 19/04. Je regarde.

**Comment by MamboJoel** [comment]
Coté UI OrderItem.service.ts s'apprête à envoyer un item de commande avec la bonne date :
![image](https://cloud.githubusercontent.com/assets/3832009/24607585/d59f57ba-1872-11e7-8adb-a5420c9eef99.png)

En revanche coté serveur il semble désérialisé avec une décalage d'une heure. Certainement lié au passage à l'heure d'été. 
`Waybis.Pinard.Sevices.OrderService.SaveItem()`
![image](https://cloud.githubusercontent.com/assets/3832009/24607480/52f5373a-1872-11e7-9a60-edaea8cd4bec.png)
Seulement je m'intérroge, on aurait dû constater un décalage de deux heures, puisque c'est ce qui nous sépare de GMT.

**Comment by Portekoi** [comment]
@MamboJoel la TImeZone est dans dure dans le fichier `lgi\lgi-pinard\Web\api\orderitem\save.aspx.vb`

**Comment by Portekoi** [comment]
Ah, on s'est croisé.

**Comment by MamboJoel** [comment]
Oui je sais. C'est un problème de sérialisation de NewtonSoft. On ne parvient pas à lui faire entendre notre timezone, il persiste à tout convertir en GMT. J'ai donc patché en ajoutant deux heures, ce qui convient à la fois pour été et hiver (ici on ne s'intéresse qu'aux jours, pas aux heures). @Portekoi si tu trouves une manière de faire comprendre à NewtonSoft notre fuseau on est preneurs.

**Comment by MamboJoel** [comment]
@RomainLGI j'ai publié un patch. Le problème est corrigé.
@Portekoi tu jettes un œil à la sérialisation ? Je ferme cette issue et on discute le topic dans [cette issue](https://github.com/ntlm-technologies/lgi-pinard/issues/5) pour ne pas polluer Romain.
Je clos.
