### ISSUE TITLE
Système d'appro - 

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#54]
Depuis ce matin, dès que nous faisons une action sur l'onglet "suivi" d'une commande (changement de statut, commentaire,...), le système nous redirige directement sur l'onglet "commande", ce qui n'était pas le cas auparavant.
Cela nous oblige à retourner sur l'onglet "suivi" après chaque action

**Comment by MamboJoel** [comment]
Je crée l'issue dans [le bon projet](https://github.com/lgi-wines/Approvisionnements/). Je ne comprends pas pourquoi tu n'y a pas accès. Je t'ai renvoyé une invitation.
[La nouvelle issue](https://github.com/lgi-wines/Approvisionnements/issues/125)

**Comment by MamboJoel** [comment]
C'est corrigé.
