### ISSUE TITLE
Appro - perte de commandes

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#55]
Les commandes d'habillages 91415 et 92812 sont dans le statut "1ere lecture conforme", et cela depuis quelques semaines déjà.
Depuis hier, quand nous filtrons pour rechercher toutes les commandes en statut "1ere lecture conforme", ces 2 commandes n'apparaissent plus dans le pool de commandes dans ce statut.

**Comment by MamboJoel** [comment]
C'est corrigé.
