### ISSUE TITLE
Problème poids carton sur liasse de commande

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#57]
Commande client #32481: le poids du carton qui apparait dans l'onglet "Liasse de commande" est 8kg, alors que le poids qui apparait dans l'onglet "Formulaire" de la fiche produit du produit concerné est de 7.194kg.
Ce qui pose problème lors de l'établissement des documents de transport car les transporteurs ne veulent pas prendre les marchandises trop lourdes!

Est-ce un problème d'arrondi? Il faut que le poids carton sur la liasse de commande soit identique à celui sur les fiches produits.

**Comment by Portekoi** [comment]
Le problème semble intervenir avant l'affichage car dans la table `product`, j'ai :
![image](https://cloud.githubusercontent.com/assets/1560754/25554392/85a32020-2ccc-11e7-8a17-2e094225e332.png)

Je regarde si je reproduis l'anomalie à la saisie.

**Comment by RomainLGI** [comment]
Salut, des nouvelles de ce problème? #portekoi

**Comment by Portekoi** [comment]
On en a parlé avec @MamboJoel mais on a pas eu le temps encore de pousser notre réflexion.

**Comment by josneaulgi** [comment]
poussez maintenant la réflexion car on est bloqué au niveau des expéditions.

**Comment by MamboJoel** [comment]
C'est corrigé.
