### ISSUE TITLE
Commentaire Transport

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#58]
si on rentre un commentaire dans le formulaire client, dans la case Commentaire transport, on n'arrive plus à l'enlever dans la commande. Ex. http://lgivm.waybis.com/Client/Form.aspx?ClientID=641, carte ID 32927

**Comment by Portekoi** [comment]
Au vu du code, ceci n'est pas possible : Si le commentaire dans le `Kart` est vide, il est automatiquement remplacé par le contenu du commentaire au niveau du client.
Solution : remplacez le contenu par un '/' par exemple.

**Comment by Portekoi** [comment]
Je reviens sur cette issue. Je pense qu'il faudrait simplement bloquer en écriture le commentaire du côté de la commande car cela signifie que cette précision n'a plus lieu d'être.
Le mieux est donc pour ce cas : 

1. De supprimer le `commentaire transport` au niveau du client et de sauvegarder
2. De supprimer le `commentaire transport` au niveau de la commande et de sauvegarder

Cela videra le cadre concerné pour toutes les commandes à venir.

**Comment by Portekoi** [comment]
Vu ce jour en réunion
