### ISSUE TITLE
PB automatisation de la CRD

### ISSUE THREAD

**Issue by RomainLGI** [lgi-wines/Extranet-LGI#59]
Fiche produit #26410
Onglet "Composant": une capsule avec CRD est sélectionnée
Onglet "Formulaire": dans l'encadré "Dénomination", le champ "CRD" apparaît comme "NON", donc la CRD n'est pas décomptée dans le "Prix de Revient total" dans l'onglet "Composant"

**Comment by MamboJoel** [comment]
C'est ok !
