### ISSUE TITLE
Compléter Tables ACTIVITY et COMPTES

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#6]
Salut Nicolas,

Voir PJ

• Table ACTIVITY 
o   Modif Activity 7 « Pris sur stock » => « Pris sur stock SLIGRO »
o   Créer Activity 14 « Pris sus stock SINGAPORE »
o   Crée Activity 15 « Pris sur stock DSJC »

• Table COMPTES
o   Modif Comment ID 78 « Sligro BIB » => « Pris sur stock SLIGRO »
o   Modif Comment ID 79 « Sligro BIB » => « Pris sur stock SLIGRO »

o   Modif ID 104, 105 et 106
 Activity 7 => Activity 15
 Comment « Pris sur stock » => « Pris sur stock DSJC »

o   Créer ID 107 et 108
 Activity 14
[Comptes.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/532643/Comptes.xlsx)

 InvoiceMode 2
 Vatlaw 3

Merci de me dire quand c’est OK

**Comment by josneaulgi** [comment]
closed for Laurent. Fait avec Jacques.
