### ISSUE TITLE
Encodage Excel

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#63]
Les états excels [du planning](http://lgivm.waybis.com/Planning2/Index.aspx?BottlerID=2) souffrent d'erreurs d'encodage.

![image](https://cloud.githubusercontent.com/assets/3832009/25900906/51e7aafe-3595-11e7-862b-c86e2cde4f85.png)

![image](https://cloud.githubusercontent.com/assets/3832009/25900968/8b749d40-3595-11e7-934b-c20d4a97d88d.png)

@Portekoi peux-tu te pencher dessus ?

**Comment by Portekoi** [comment]
Corrigé et livré. Exemple avec le fichier ci-joint. 
[issu63.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1003794/issu63.pdf)

Un CTRL + F5 sera peut être nécessaire.

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
Je viens de faire un essai de téléchargement et le problème persiste.
Philippe

**Comment by Portekoi** [comment]
@LEBRUNPhilippe  : Quand on clique sur "ligne A", c'est bon.

A l'inverse, je n'avais pas corrigé pour le lien "xls des consommations de vin". Je regarde.

**Comment by Portekoi** [comment]
C'est corrigé et livré pour  le lien "xls des consommations de vin".
Voir ci-joint.

**Comment by LEBRUNPhilippe** [comment]
Tout OK. Merci
