### ISSUE TITLE
Nouvelles capacités des lignes d'embouteillage

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#69]
- Ligne A: 80000 cols
- Ligne B: 50000 cols
Retirer la capacité par nombre de mises.

**Comment by Portekoi** [comment]
J'ai trouvé la table `ManufacturingLine` : 
![image](https://cloud.githubusercontent.com/assets/1560754/26471618/9f5a5796-41a2-11e7-85a6-13d1f1082aba.png)

Logiquement, si je modifie la valeur de l'ID 1 à 80000 et l'ID à 50000, cela devrait être bon. Mais je préfère avoir confirmation par @MamboJoel avant d'agir.

**Comment by MamboJoel** [comment]
Tu peux y aller. Et retirer, à l'affichage, la capacité par nombre de mises.

**Comment by Portekoi** [comment]
Capacité modifiée
````
 update [Pinard].[dbo].[ManufacturingLine]
 set DayUnitCapacity = 80000 
  Where ManufacturerID = 2
  And Code = 'A'

 update [Pinard].[dbo].[ManufacturingLine]
 set DayUnitCapacity = 50000  
  Where ManufacturerID = 2
  And Code = 'B'

```

Pour validation : 
![image](https://cloud.githubusercontent.com/assets/1560754/26587856/de40cdb4-4553-11e7-9dd5-6f3d42b84670.png)

**Comment by LEBRUNPhilippe** [comment]
OK pour moi

**Comment by Portekoi** [comment]
C'est livré.
