### ISSUE TITLE
Création Utilisateur JOSNEAU Stéphanie (Resp. ADV)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#7]
Créer Utilisateur JOSNEAU Stéphanie

stephanie.josneau@lgi-wines.com

Responsable Service ADV

**Comment by MamboJoel** [comment]
Je lui ai envoyé l'invitation.

**Comment by lgazeau** [comment]
Salut Nicolas,

Désolé, mais Stéphanie n'a pas reçu ton invitation.
Merci de lui renvoyer à stephanie.josneau@lgi-wines.com

**Comment by MamboJoel** [comment]
Je viens de l'envoyer de nouveau.

**Comment by josneaulgi** [comment]
Tout est ok, comment fermer le ticket? mettre en statut closed?

**Comment by MamboJoel** [comment]
Bonne question Stéphanie. Je t'ai envoyé une invite pour lgi-wines avec les droits pour pouvoir clore les tickets. Dans l'idéal leur clôture relève plutôt de celui qui l'a ouvert, quand il est satisfait.
Je ferme celui-ci.
