### ISSUE TITLE
Le BF s'étend sur deux pages

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#71]
Par exemple [cette mise](http://lgivm.waybis.com/Manufacturing/FabricationBill.aspx?ManufacturingID=184899) s'étale sur deux pages :

![image](https://cloud.githubusercontent.com/assets/3832009/25901428/13e60d5c-3597-11e7-996d-558c7b6d0c77.png)

@Portekoi, si tu peux regarder ?

**Comment by Portekoi** [comment]
Ok. Corrigé et livré. Ci-joint "Avant / Après"
[Avant - Bon de fabrication.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1005873/Avant.-.Bon.de.fabrication.pdf)
[Après - Bon de fabrication.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1005874/Apres.-.Bon.de.fabrication.pdf)

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
La modification a fonctionné sur la fiche en question mais j'ai vérifié sur une autre fiche (mise 185227, fiche produit N°26451) et ça ne tient pas sur une page.
Philippe

**Comment by Portekoi** [comment]
Sur ce second cas, j'ai peur de ne pas pouvoir y arriver. 
@LEBRUNPhilippe Pouvez-vous m'indiquer si des lignes ne servent plus dans le document? (s'il y en a)
Cela me permettrait de mieux refaire ce document.

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
C'est à mon avis Gênant d'enlever d'autres lignes, peut être pourrais-tu enlever le visuel de la bouteille qui est tout en haut à droite de la fiche.

**Comment by Portekoi** [comment]
Je vais regarder. Est ce que je peux changer la disposition de l'entête?

**Comment by Portekoi** [comment]
C'est corrigé et publié pour le 185227. J'ai du  modifier l 'entête,  réduire un peu la police et trouver le bon ratio pour la police afin  de garder les infos essentielles en gros. 
@LEBRUNPhilippe Dites moi si cela vous convient :
http://lgivm.waybis.com/Manufacturing/FabricationBill.aspx?ManufacturingID=185227

Je joins un PDF d'exemple
Avant :
[Bon de fabrication-avant.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1037855/Bon.de.fabrication-avant.pdf)

Après :
[Bon de fabrication.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1037853/Bon.de.fabrication.pdf)

**Comment by LEBRUNPhilippe** [comment]
J'ai fait un essai d'impression depuis way bis sur cette fiche 185227 et la police est vraiment réduite.
Les écritures n'encombrent que 80 % de la hauteur de la page.
Pourrais-tu réaugmenter un peu la police et je regarde ce que ça donne. Merci

**Comment by Portekoi** [comment]
Je reviens vers 14h. Mon pdf n'est pas bon quand tu l'imprimes?

**Comment by Portekoi** [comment]
@LEBRUNPhilippe  Je viens de la grossir un peu. (+0.1)
On repasse sur deux pages mais si tu me dis que ça te va, je vais en sorte que cela reste sur une page.

**Comment by LEBRUNPhilippe** [comment]
Je pense qu'on imprime pas cette fiche à partir du même endroit car je n'ai pas la même mise en page que sur ton PDF. Personnellement, j'imprime à partir de l'onglet "bon de fabrication". Est-ce que ton PDF n'est pas issu de l'onglet "bon de fabrication UCC"? Peux tu essayer de grossir plus car je n'ai pas vu de changement par rapport à ce matin. Merci

**Comment by Portekoi** [comment]
Peux tu vider ton cache (CTRL + F5) ?

Tu es bien sous Chrome? Sur ce lien, que vois tu? :
http://lgivm.waybis.com/Manufacturing/FabricationBill.aspx?ManufacturingID=185227

**Comment by Portekoi** [comment]
Ou appelle moi si tu peux/veux que l'on règle cela rapidement : 06 15 94 89 12

**Comment by Portekoi** [comment]
J'y suis presque...
![image](https://cloud.githubusercontent.com/assets/1560754/26585643/001df094-454d-11e7-99f7-18c23eda0713.png)

**Comment by Portekoi** [comment]
@LEBRUNPhilippe C'est tout bon. N'oublie pas de refaire un CTRL+F5.

J'ai dû raboter un peu le bas. J'espère que cela te conviendra.

Ci-joint le résultat en PDF.
[Bon de fabrication - 1p.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1038491/Bon.de.fabrication.-.1p.pdf)

**Comment by LEBRUNPhilippe** [comment]
C'est tout bon, je ne clos pas encore, je ferai quelques vérifications. Merci

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
J'ai une demande pour la mise en page, par exemple, sur la fiche 25360:
Dans le haut de page apparait la mention "QUANTITE : Label", est-ce que le mot "label" peut être enlevé?
Ensuite, le nom du client a été décalé sur la droite "CLIENT CONCERNE : MATTHEW CLARK Royaume-Uni", est-il possible de le réaligner sur la gauche?
Merci.

Philippe

**Comment by Portekoi** [comment]
Bonjour @LEBRUNPhilippe ,
Je viens de corriger le bogue avec "Label" ainsi que le cadrage du client à droite que j'ai repassé à gauche.

Important : si le commentaire figurant en haut à gauche du document dépasse les 200 caractères, le BF pour la mise 185227 passera sur 2 pages. 

Là, on est juste comme il faut. Dis moi si cela te convient.

**Comment by LEBRUNPhilippe** [comment]
Bonjour,
C'est parfait.
Merci, je clos.
