### ISSUE TITLE
Inventaire : afficher les mouvements des 12 derniers mois

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#75]
Sur [cette page](http://lgivm.waybis.com/StockInventory/Form.aspx?StockInventoryID=14233).

**Comment by Portekoi** [comment]
Pour cette issue, j'ai fait les modifs mais je ne trouve pas de cas pour vérifier.
[Cet exemple](http://localhost:43044/StockInventory/Form.aspx?StockInventoryID=14233) me retourne aucune ligne

**Comment by Portekoi** [comment]
[Ok, j'ai trouvé un exemple](http://lgivm.waybis.com/StockInventory/Form.aspx?StockInventoryID=36295)
Je livre et je vérifie.

**Comment by Portekoi** [comment]
@LEBRUNPhilippe Merci de checker si c'est bon pour toi

**Comment by LEBRUNPhilippe** [comment]
c'est ok, je ferme cette issue
