### ISSUE TITLE
Suppression des menus "Conf. Transporteur (Client)" et "Conf. Transporteur (Client) PDF"

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Extranet-LGI#79]
Suppression des menus "Conf. Transporteur (Client)" et "Conf. Transporteur (Client) PDF" suite à notre entrevue du 4 mai dernier. Vu avec le service ADV

**Comment by josneaulgi** [comment]
Bonjour,
yes, tu peux supprimer ces deux menus.
merci
Stéphanie

**Comment by Portekoi** [comment]
Fait.

**Comment by josneaulgi** [comment]
ATTENTION !!! il ne reste que la version PDF des Conf Transporteur (Trans) qui n'est pas dans la bonne mise en page !! merci de remettre la version originale et de corriger la version pdf.

**Comment by josneaulgi** [comment]
URGENT URGENT URGENT : je ne peux pas envoyer de dispo !!!!!!!!!!! l'onglet Conf Transporteur (Trans) n'existe qu'en version PDF alors que je n'avais pas demander de supprimer la version originale !! et la version PDF n'est pas du tout lisible !! Merci de vérifier avant de mettre en application.

**Comment by Portekoi** [comment]
@josneaulgi Je viens de relivrer. Je suis désolé, je n'ai pas vu le mail d'hier à 16h44.
Pour le PDF, je pense que la version PDF a été écrasée. Je vais regarder.

**Comment by josneaulgi** [comment]
ok merci

**Comment by Portekoi** [comment]
@josneaulgi  J'ai mis en ligne la version "PDF" sans toucher à la version "non PDF" et j'ai bien contrôlé.
Pouvez-vous tester ma version PDF et me dire si cela vous va? Merci

**Comment by Portekoi** [comment]
@josneaulgi Avez-vous pu tester?

**Comment by josneaulgi** [comment]
ok c'est bon. Idem pour les factures en PDF.
