### ISSUE TITLE
Conversion de la page "Packing List" en PDF

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Extranet-LGI#80]
Conversion de la page "Packing List" en PDF / Demande ADV

**Comment by josneaulgi** [comment]
la version PDF ne correspond pas à la version d'origine.
problème de mise en page comme on avait eu avec la facture.
merci de corriger.

**Comment by Portekoi** [comment]
Je viens de publier la version pdf. Voir ci-joint.
A noter que je n'ai pas modifié la version "non pdf".
[Kart_PackingListPDF_31278.pdf](https://github.com/lgi-wines/Extranet-LGI/files/1029035/Kart_PackingListPDF_31278.pdf)

Lien direct : http://lgivm.waybis.com/uploads/Karts/Kart_PackingListPDF_31278.pdf

**Comment by josneaulgi** [comment]
ok
