### ISSUE TITLE
Prise en compte Modifs PRODUITS par ADV

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#81]
J'ai une URGENCE. 

2 des filles de l'ADV passent entre 1h30 et 2h00 chaque matin à contrôler les données financières de toutes les COMMANDES SAISIES la veille et de toutes les COMMANDES FACTURÉES la veille  (Départs).

Les rares erreurs ne concernent que des PRODUITS SOUCHES modifiées par le service PRODUITS (Login Romain Sandra et Eric R.) dont le Service ADV (Login Stéphanie Pauline et Alexandra) n'a pas eu connaissance ; et dont il ne revalide donc pas les 3 éléments qui sont encore aujourd'hui de son ressort (Prix de Vente, Budget, Commission Agent). 

Rappel : Le Service PRODUIT a obligation de repasser le statut du produit de "Actif" à "Projet" pour pouvoir modifier un produit. Cette modif est donc trackée dans l'Appli.

Pour supprimer purement et simplement ces contrôles (1h30 et 2h00 / jour x 2 personnes) nous voudrions que les tous les produits souches modifiés par le Service PRODUIT apparaissent avec un "point rouge" dans la liste des produits du client.
L'ADV se chargera de revalider le produit au moment de  le passer dans une commande, en checkant les 3 données qui sont les siennes (Prix de Vente, Budget, Commission Agent).   Cette validation transformera le "point rouge" en "point vert" (qui signifie "validé ADV).

Pour les produits commandés non partis, l'ADV fait son affaire des modifs à partir d'un "Annule et Remplace" (aller-retour de statuts de la commande "Transmise => Validée => En-cours de Saisie => Validée => Transmise à la cave") qu'elles disent bien gérer et suivre (notamment au niveau de ré-génération des mises), sans en omettre.

Seule contrainte à mettre en place : L'ADV ne doit pas pouvoir saisir une commande avec un produit "point rouge".

Dans le futur environnement nous gérerons de façon dynamique "Validation Commerciale" "Validation Service PRODUITS" et "Validation ADV" (qui n'aura cependant plus lieu d'être puisque le Commercial aura validé (Prix de Vente, Budget et Commission Agent).

**Comment by MamboJoel** [comment]
Ok Laurent. Est-ce qu'on peut s'appeler demain après-midi pour ça ?

**Comment by lgazeau** [comment]
Suis au bureau toute la journée.
A ta disposition.
Tu m'appelles quand tu veux.
@ toute a l'heure.

**Comment by lgazeau** [comment]
...au départ TOUS les produits sont donc "Point Rouge" et au fur à mesure où ils seront à passer dans les commandes, l'ADV les passera en "Point Vert" (validé ADV)
Il n'y aura rapidement plus que des "Points Verts"

**Comment by MamboJoel** [comment]
Ok j'ai publié.
