### ISSUE TITLE
Composant "Etiquette" et "Contre étiquette"

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#82]
Depuis jeudi dernier, quand nous cliquons et entrons dans un composant étiquette ou contre étiquette nous arrivons directement sur le 2ème onglet "Stock", alors qu'avant nous arrivions sur le 1er onglet "Formulaire".

Il faudrait que l'on retombe directement sur le 1er onglet "Formulaire"

Merci

**Comment by MamboJoel** [comment]
C'est une [demande](https://github.com/lgi-wines/Extranet-LGI/issues/76) lors de la réunion du 4.

**Comment by MamboJoel** [comment]
On a inversé.
