### ISSUE TITLE
Extraction de données Manoir Grignon

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Extranet-LGI#83]
Message d'origine de Céline :

> Salut Nicolas,
>  
> Suite à ma demande peux-tu générer un tableau Excel avec les éléments ci-dessous, pour la Marque MANOIR GRIGNON ?
>  
> Attention, j’ai uniquement besoin des produits ACTIFS.
>  
> Tableau # 1 => CE Manoir Grignon
> Composant CE
> ID CE
> Code CE
> Client
> Produit
>  
> Tableau # 2 => caisse Perso Manoir Grignon
> Composant Caisse
> ID Caisse
> Client
> Produit

**Comment by MamboJoel** [comment]
Je ne trouve pas de caisse ayant pour nom "caisse Perso Manoir Grignon" ou "Perso Manoir Grignon". Peux-tu me passer l'ID du composant ?

**Comment by celinelgi** [comment]
Idem pour les CE, il y en a 42:
![image](https://cloud.githubusercontent.com/assets/22617509/26357656/4220e532-3fd0-11e7-901c-d285d84f1100.png)

**Comment by MamboJoel** [comment]
J'ai envoyé ces données par mail.
