### ISSUE TITLE
Pas possible d'enregistrer les PDFs dans le Cloud

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#85]
les PDFs des factures, packing list et conf transporteur (trans) sont corrects mais je n'arrive pas à les enregistrer dans le Cloud.

**Comment by MamboJoel** [comment]
Il n'y a pas de menu "Fichier > Enregistrer sous" ?
A ce stade, on n'a plus la main. L'application a généré un fichier, il se trouve sur votre ordinateur, ouvert par votre logiciel de lecture des PDF et nous n'avons pas accès à cela.
@Portekoi une idée ?

**Comment by Portekoi** [comment]
Non aucune. Normalement, il y a le logo pour télécharger le PDF et nous perdons la main sur ce qu'il se passe ensuite.

![image](https://cloud.githubusercontent.com/assets/1560754/26547993/158eb674-4472-11e7-91ff-d70addaaabcd.png)

**Comment by josneaulgi** [comment]
bonjour,
serait-il possible lorsqu'on clique sur Facture PDF, que le téléchargement se fasse automatiquement et se mette dans l'ordi dans téléchargement ou dans un dossier sur le bureau ?

**Comment by Portekoi** [comment]
Bonjour,
Le plus simple serait de faire un "clic droit" sur le lien désiré puis "enregistrer sous" : 

![image](https://user-images.githubusercontent.com/1560754/27585428-82d7d450-5b3c-11e7-9c0c-aa8463b52650.png)

**Comment by Portekoi** [comment]
@josneaulgi Je n'ai hélas pas trouvé de solution car cela sort du navigateur et nous ne pouvons pas contrôler cela. Je clos.
