### ISSUE TITLE
Type de composant "Edulcoration" => pas de calcul de prix total dans les "Bon d'achat" selon le nombre de bouteilles

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#87]
### Description
Pour les produits en prestation de service sur les mises extérieures (hors UCC), nous contrôlons les factures que nous envoient nos embouteilleurs via le "Bon d'achat" de WB. Cependant, quand nous mettons de l'édulcoration (Type de composant "Edulcoration"), le calcul total (lié au nombre de bouteille) n'est pas fait sur le bon d'achat- donc on retrouve toujours 0€

### Scénario pour reproduire l'anomalie
Pour retrouver le bon d'achat: taper "184264" dans l'onglet "Mises" de WB / cliquer sur l'onglet "Fiche d'achat 3S - PRESTATION" / le bon d'achat s'ouvre => la première ligne "Edulcoration en G/HL" affiche "0.00 kg". Le prix "P.U.€" est bien renseigné (0.0285).

### Résultat attendu
Dans la fiche produit d'origine sur laquelle a été saisie la commande 27745, à la 3ème ligne de composant ("Edulcoration"), nous avons mis "500%", ce qui correspond à 5 g/Hl et donc bien à 0.0285€ par bouteille. Cet élément se reporte bien sur le bon d'achat.

Sur le bon d'achat, dans la colonne quantités, il faudrait reporter le nombre de bouteilles total (comme sur les composants qui suivants) pour que le bon d'achats calcule le nombre de bouteille x le P.U.€ (0.0285€ dans ce cas) = Total HT €

### Anomalie constatée
Le total HT€ de la ligne Edulcoration n'est pas bon car le P.U.€ n'est pas multiplié par le nombre de bouteilles

**Comment by MamboJoel** [comment]
Doublon : #88
