### ISSUE TITLE
Type de composant "Edulcoration" => pas de calcul de prix total dans les "Bon d'achat" selon le nombre de bouteilles

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#88]
### Description
Pour les produits en prestation de service sur les mises extérieures (hors UCC), nous contrôlons les factures que nous envoient nos embouteilleurs via le "Bon d'achat" de WB. Cependant, quand nous mettons de l'édulcoration (Type de composant "Edulcoration"), le calcul total (lié au nombre de bouteille) n'est pas fait sur le bon d'achat- donc on retrouve toujours 0€

### Scénario pour reproduire l'anomalie
Pour retrouver le bon d'achat: taper "184264" dans l'onglet "Mises" de WB / cliquer sur l'onglet "Fiche d'achat 3S - PRESTATION" / le bon d'achat s'ouvre => la première ligne "Edulcoration en G/HL" affiche "0.00 kg". Le prix "P.U.€" est bien renseigné (0.0285).

### Résultat attendu
Dans la fiche produit d'origine 27745 sur laquelle a été saisie la commande, à la 3ème ligne de composant ("Edulcoration"), nous avons mis "500%", ce qui correspond à 5 g/Hl et donc bien à 0.0285€ par bouteille. Cet élément se reporte bien sur le bon d'achat.

Sur le bon d'achat, dans la colonne quantités, il faudrait reporter le nombre de bouteilles total (comme sur les composants qui suivants) pour que le bon d'achats calcule le nombre de bouteille x le P.U.€ (0.0285€ dans ce cas) = Total HT €

### Anomalie constatée
Le total HT€ de la ligne Edulcoration n'est pas bon car le P.U.€ n'est pas multiplié par le nombre de bouteilles

**Comment by MamboJoel** [comment]
Salut Romain, 

Merci pour le problème bien décrit. On touche à des règles métier établies il y a longtemps et qui sont très utilisées dans l'application (les quantités et les unités), il risque d'y avoir des changements un peu partout. La quantité de l'édulcoration était sciemment passée à 0. 

- En retirant cette règle la première chose qui survient c'est qu'elle est exprimée en kg. Ici un peu plus de 5 kg. 
- En changeant l'unité de l'édulcoration pour la passer au col (ce qui d'instinct me semble suspect mais soit) j'obtiens le BA suivant :

![image](https://cloud.githubusercontent.com/assets/3832009/26781860/e98464e6-49f0-11e7-82a2-92d44a1ea313.png)

Est-ce que ça te convient ? Sachant que cela risques d'avoir un impact un peu partout dans l'application. On pourra toujours revenir en arrière cela dit.

Est-ce qu'on tord pas un peu la réalité ?

**Comment by lgiRomain** [comment]
Salut Nicolas,



Oui le résultat final est conforme. Il est logique d’avoir la multiplication 
faite via le nombre de cols car l’unité de calcul est le « P.U.€ » qui est 
le cout à la bouteille.

Pour moi c’est très bien comme cela.



On sera vigilent dans le futur pour voir ce que ce changement aurait pu 
créer comme nouveau problème.



Merci

Romain MOSTACCHI

LGI Product Service

+33 468 119 591



De : Nicolas Taret [mailto:notifications@github.com]
Envoyé : lundi 5 juin 2017 13:15
À : lgi-wines/Extranet-LGI <Extranet-LGI@noreply.github.com>
Cc : lgiRomain <romain.mostacchi@lgi-wines.com>; Author 
<author@noreply.github.com>
Objet : Re: [lgi-wines/Extranet-LGI] Type de composant "Edulcoration" => pas 
de calcul de prix total dans les "Bon d'achat" selon le nombre de bouteilles 
(#88)



Salut Romain,

Merci pour le problème bien décrit. On touche à des règles métier établies 
il y a longtemps et qui sont très utilisées dans l'application (les 
quantités et les unités), il risque d'y avoir des changements un peu 
partout. La quantité de l'édulcoration était sciemment passée à 0.

*	En retirant cette règle la première chose qui survient c'est qu'elle est 
exprimée en kg. Ici un peu plus de 5 kg.
*	En changeant l'unité de l'édulcoration pour la passer au col (ce qui 
d'instinct me semble suspect mais soit) j'obtiens le BA suivant :

**Comment by MamboJoel** [comment]
C'est implémenté et publié. On suit l'évolution et le cas échéant on réouvre cette issue.
