### ISSUE TITLE
Mauvaises appellations sur le planning de mises hors GVSC

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#89]
### Description
Dans le planning de mises en bouteille hors GVSC, certains produits ressortent avec une mauvaise appellation

### Scénario pour reproduire l'anomalie
Cliquer sur l'onglet "Commandes" de WayBis / Ouvrir l'Excel nommé "XLS planning d'embouteillage hors GVSC " / Dans les lignes 60, 61 et 62 par exemple (embouteilleur Alliance Terroirs, client Grandly Pacific), dans la dernière colonne "Appellation", c'est une mauvaise appellation qui ressort "IGP Pays d'Hérault"

### Résultat attendu
L'appellation pour ces produits devrait être "IGP Pays d'Oc", voir les onglets "Formulaires" des fiches produits 28264 et 28315 sur lesquelles les commandes ont été saisies.

### Anomalie constatée
Une mauvaise appellation remonte dans le tableau des mises hors GVSC

**Comment by Portekoi** [comment]
Ci-joint avec une correction en locale. Si vous me dite que c'est tout bon, je publie.

[Hors-GVSC-LGI_à_planifier_au_157-6-2017.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1055472/Hors-GVSC-LGI_a_planifier_au_157-6-2017.xlsx)
[GVSC-LGI_à_planifier_au_157-6-2017.xlsx](https://github.com/lgi-wines/Extranet-LGI/files/1055473/GVSC-LGI_a_planifier_au_157-6-2017.xlsx)

**Comment by lgiRomain** [comment]
A priori c'est réglé. 
Je reviens vers toi si le problème se présente à nouveau à l'avenir.

Merci
