### ISSUE TITLE
Qualification lignes OD de l'Escompte générée par le LETTRAGE

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Extranet-LGI#90]
La création d'un Avoir d'ESCOMPTE automatique par l'onglet lettrage crée une commande sans produit dont l'OD port l'ID=8 "Commission" dans KartDetailType alors que ce devrait être ID=7 "Discount"

Exemple : KartID 32184

Merci de corriger

**Comment by MamboJoel** [comment]
Le comportement actuel lors d'un lettrage avec delta discount :
- On crée un `Kart`.
- On lui ajoute un `KartDetail`.
- Celui-ci n'a pas de `KartDetailType`
- Quand l'utilisateur se rend sur [la page de la commande](http://lgivm.waybis.com/Kart/Form.aspx?KartID=32184), la boîte de sélection ne trouve pas de `KartDetailType` correspondant et affiche par défaut le premier : "Commission".
![image](https://user-images.githubusercontent.com/3832009/26887019-33eebf92-4ba7-11e7-8b05-5e264f1b940a.png)
- Lorsqu'il clique sur "Enregistrer" la valeur commission est enregistrée.

**Comment by MamboJoel** [comment]
Désormais on affecte la veleur "Escompte" au `KartDetailType` au moment du lettrage.
