### ISSUE TITLE
URGENT !!! Problème tarif palette (on ne peut plus rien saisir tant que ce n'est pas réglé)

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#94]
### Description
Sur l'ensemble des fiches produits, les prix des palettes ne sont plus divisés par mille, donc si on met 12€ la palette par exemple, cela compte 12€ en plus sur le PR du produit au lieu de 0.012€

### Scénario pour reproduire l'anomalie
Ex: fiche numéro 28318

### Résultat attendu
Le prix de la palette doit être divisé par 1000 pour une bouteille

### Anomalie constatée
Le prix de la palette sur reporte sur le prix d'une bouteille

**Comment by Portekoi** [comment]
Il s'agit de cette modification : 
https://github.com/lgi-wines/Approvisionnements/issues/163

**Comment by Portekoi** [comment]
Je vais voir pour faire marche arrière.

**Comment by Portekoi** [comment]
J'ai remis l'unité à 1000 pour les palettes mais du coup, cette issue est de nouveau à traiter : 
https://github.com/lgi-wines/Approvisionnements/issues/163

**Comment by josneaulgi** [comment]
Le prix unitaire de la palette est bien correct, par contre le résultat n'est toujours pas bon car il faut multiplier le coût unitaire de la palette par le nombre de bouteilles.
Ex : mise 187477 : 23040bts x 0.012 = 276.48€ (et non 384€)
http://lgivm.waybis.com/Kart/PurchaseOrder.aspx?ManufacturingID=187477&exManufacturingID=187477&exSupplierID=246

**Comment by MamboJoel** [comment]
@Portekoi je suis en réunion, est-ce que tu peux jeter un oeil ? C'est peut-être un mismatch de versions.

**Comment by Portekoi** [comment]
@josneaulgi La correction a eu lieu il y a environ 15 jours.

Est ce que le résultat était bon jusqu'à hier ou un peu avant ou jamais?

**Comment by josneaulgi** [comment]
jamais

**Comment by Portekoi** [comment]
*** Problème rencontré
Dans la classe BaseProductComponent, la propriété TotalPrice : 

```
Public ReadOnly Property TotalPrice() As Decimal
	Get
		If Product.GetType = GetType(KartProduct) Then
			Select Case Component.ComponentType
				Case ComponentType.Edulcoration
					Return UnitPrice * CType(Product, KartProduct).TotalNumberOfBottles
				Case ComponentType.Pallet
					Return UnitPrice / 1000 * CType(Product, KartProduct).TotalNumberOfBottles
				Case Else
					Return UnitPrice * Quantity
			End Select
		Else
			Return UnitPrice * Quantity
		End If
	End Get
End Property

```

 renvoie ce calcul : 
`Return UnitPrice * Quantity` (car dans à ce niveau, nous ne sommes pas dans un KartProduct)

Mais à ce stade, nous ne connaissons pas le nombre de bouteilles puisque nous sommes au niveau du composant lui-même.

J'ai donc essayé de modifier l'affichage lui-même mais les totaux pour le fournisseur sont faux car ils sont calculés grâce à la méthode `Product.GetSupplierCosts(Supplier.ID)` qui fait un `For Each` sur tous les composants et additionne pour chaque, le fameux `TotalPrice`

*** Solution

J'ai eu trop de problèmes en modifiant la propriété `TotalPrice` et je suis un peu frileux de le refaire.

`TotalPrice` semble utilisée uniquement pour les `Supplier` donc je ferai une méthode CalcTotalPrice() dans `BaseProductComponent` en transmettant le nombre de bouteilles puis en testant la nature du composant. Si Différent de `Pallet`, alors je laisse le `UnitPrice * Quantity`, sinon, j'applique le `(UnitPrice/1000) * NumberOfBottles` 

C'est peu élégant mais je ne vois pas comment faire autrement.

**Comment by Portekoi** [comment]
J'ai trouvé une propriété `productQuantitySimulation` dans `BaseProductComponent` et qui semble contenir le nombre de bouteilles.

J'ai modifié comme ceci mais je ne sais pas comment être certain que cela fonctionne : 

```
    Public ReadOnly Property TotalPrice() As Decimal
        Get
            If Product.GetType = GetType(KartProduct) Then
                Select Case Component.ComponentType
                    Case ComponentType.Edulcoration
                        Return UnitPrice * CType(Product, KartProduct).TotalNumberOfBottles
                    Case ComponentType.Pallet
                        Return UnitPrice / 1000 * CType(Product, KartProduct).TotalNumberOfBottles
                    Case Else
                        Return UnitPrice * Quantity
                End Select
            Else
                If Component.ComponentType = ComponentType.Pallet Then
                    If productQuantitySimulation.HasValue Then
                        Return UnitPrice / 1000 * productQuantitySimulation
                    Else
                        Return UnitPrice * Quantity
                    End If
                    Return UnitPrice * productQuantitySimulation
                Else

                    Return UnitPrice * Quantity
                End If
            End If
        End Get
    End Property
```

Je n'ai pas commité (Souci avec **AWS**)

**Comment by MamboJoel** [comment]
J'ai publié le patch de Damien. Est-ce que ça vous convient ?

**Comment by josneaulgi** [comment]
OK, c'est bon
