### ISSUE TITLE
Attention impossible de créer un marque dans WB. Onglet "Paramétrage" de WB, bouton "Créer une marque" => message d'erreur

### ISSUE THREAD

**Issue by lgiRomain** [lgi-wines/Extranet-LGI#95]
Attention impossible de créer un marque dans WB. Onglet "Paramétrage" de WB, bouton "Créer une marque" => message d'erreur

**Comment by Portekoi** [comment]
C'est corrigé : http://lgivm.waybis.com/Make/Form.aspx?MakeID=987
