### ISSUE TITLE
Demande rajout du degré d'alcool sur la delivery Note

### ISSUE THREAD

**Issue by josneaulgi** [lgi-wines/Extranet-LGI#98]
merci de rajouter le degré d'alcool sur la delivery note (comme sur la packing list)
http://lgivm.waybis.com/Kart/DeliveryNote.aspx?KartID=33570
merci

**Comment by josneaulgi** [comment]
relance

**Comment by MamboJoel** [comment]
C'est bon.

**Comment by Portekoi** [comment]
@MamboJoel Je vois pas ton commit là dessus. 

https://github.com/lgi-wines/Extranet-LGI/issues/107
